---
title: "CLIF_paralytics_incidence_analysis"
output:
  html_document:
    df_print: paged
---
#This File is Run AFTER the Cohort Identification R Markdown ('cohort_identification_paralytics_incidence.Rmd')
#Specify File Paths, Project Path and Site - SITE SPECIFIC
#Load the Analytic File

```{r Load Needed Libraries, include=FALSE}
packages <- c("lubridate", 
              "tidyverse", 
              "dplyr",
              "tableone", 
              "readxl", 
              "arrow", 
              "collapse", 
              "data.table",
              "viridis",
              "sandwich", #Cluster Robust Standard Errors
              "lmtest",  #Allows Calculation of Cluster Robust Standard Errors
               "tibble",
              "gtsummary",
              "ggforce", 
              "yaml", 
              "rprojroot",
              "purrr",
              "broom"
              ) 

install_if_missing <- function(package) {
  if (!require(package, character.only = TRUE)) {
    install.packages(package, dependencies = TRUE)
    library(package, character.only = TRUE)
  }
}

sapply(packages, install_if_missing)
rm(packages, install_if_missing)

#Use Dplyr select as default
select <- dplyr::select

{ # Load config to specify local paths
    cat("Load config to specify local paths\n")
    # Find project root
    project_root <- find_root(rprojroot::has_dir("config"))
    
    # Read YAML config
    config <- yaml::read_yaml(file.path(project_root, "config", "config.json"))

    # Assign config values to R variables
    tables_location <- config$tables_path
    project_location <- config$project_location
    site <- config$site_name
    site_time_zone <- config$time_zone
    file_type <- config$file_type
    hospital_names<- config$hospital_names
  
    rm(config)
  } 


#Check timezone
check_timezone <- function(site_timezone, intended_timezone = Sys.timezone()) {
  if (site_timezone != intended_timezone) {
    cat("Warning: You specified", site_timezone, "but your system time zone is", intended_timezone, "\n")
    response <- readline(prompt = "Was that intentional? (yes/no): ")
    
    if (tolower(response) %in% c("no", "n")) {
      new_timezone <- readline(prompt = "Please enter the correct timezone: ")
      cat("Timezone updated to", new_timezone, "\n")
      return(new_timezone)
    } else {
      cat("Proceeding with the originally specified timezone:", site_timezone, "\n")
      return(site_timezone)
    }
    
  } else {
    cat("Timezone is set to", site_timezone, "\n")
    return(site_timezone)
  }
}

#Time Zone Check
result <- check_timezone(site_time_zone)

#Create Sub Folders for supplemental files within Project Output Folder
# Check if the output directory exists; if not, create it
if (!dir.exists(paste0(project_location, "/project_output_UPLOAD"))) {
  dir.create(paste0(project_location, "/project_output_UPLOAD"))
}

```

```{r Function to Convert Datetimes to Local Time Zone}
#Write Function to Convert Datetime Columns to 'UTC'
fn.timezone_tolocal <- function(df) {
  # Get the dataset schema
  sch <- df$schema
  #Which Fields are Datetime Types?
  datetime_fields <- keep(sch$fields, function(field) {
    grepl("^timestamp", field$type$ToString())
  })
  # Extract the names of these datetime columns
  datetime_cols <- map_chr(datetime_fields, "name")
  
  #Now Convert DateTime Columns to Local Timezone
  df <- df %>%
    mutate(across(all_of(datetime_cols), ~ cast(.x, arrow::timestamp("us", site_time_zone)))) |>
    compute()
}
```


```{r Load Site-specific analytic data set and Convert to Local Time Zone}
#NOTE: This Table is Created by the prior script
rose_analytic_df <- open_dataset(paste0(project_location, '/project_tables_DO_NOT_UPLOAD/rose_analytic_data.parquet'))

#Apply Function to Convert to Local Timezone
rose_analytic_df <- fn.timezone_tolocal(rose_analytic_df)

set.seed(32284) #For Reproducibility

rose_analytic_df <- rose_analytic_df |> 
  filter(!is.na(days_admit_to_enroll)) |>
  mutate(counter=1,
  tv_cc_kg=set_tv_enrollment / study_weight_kg, 
  early_prone = fifelse(as.POSIXct(first_prone_time) <= as.POSIXct(t_rose_first), 1, 0), #Final potential Exclusion, if proned at time of meeting criteria
  prone_48 = (as.POSIXct(first_prone_time)<=as.POSIXct(t_rose_first)+dhours(48)), #includes early prone before meeting criteria
  prone_48 = fifelse(prone_48==FALSE | is.na(prone_48), 0, 1), 
  prone_all = fifelse(is.na(prone_episodes), 0, 1), 
  p_and_p = fifelse(prone_48==1 & any_paralytic_48==1, 1, 0),
  pfround = round(first_rose_pf_all),
  mv_obsround = round(mv_obs_max),
  deep_rass = case_when(min_rass12< -3~1, min_rass12>-4~0), #ever in coma 12 hours
  deep_rass_max = case_when(max_rass12< -3~1, max_rass12>-4~0), #always in coma 12 hours
  min_ph = round(min_ph, digits=2),
  ph_715 = case_when(is.na(min_ph) | min_ph >=7.15 ~0, min_ph <7.15~1), 
  ph_72 = case_when(is.na(min_ph) | min_ph >=7.2 ~0, min_ph <7.2~1), #for ph cutoff sensitivity analysis
  dys_rr = case_when(as.numeric(rr_diff_max)>15~1, as.numeric(rr_diff_max) <16 ~0), 
  dys_mv = case_when(mv_obs_max <16 ~0, mv_obs_max >= 16~1), 
  agitated_rass = fifelse(max_rass12 >1, 1,0), #ever rass >1
  hypoxemia = fifelse(pfround <100, 1, 0), 
  code_status_presume = fifelse(!is.na(code_status_category), code_status_category, "Full"), 
risk_factors_meet_criteria_no_prone=case_when(ph_715==1 & hypoxemia==1  ~"Hypoxemia, Low pH", ph_715==0 & hypoxemia==1 ~"Hypoxemia", ph_715==1 &   hypoxemia==0  ~"Low pH",  ph_715==0 &  hypoxemia==0~"None"), 
risk_factors_meet_criteria=case_when(ph_715==1 & hypoxemia==1 & early_prone==1 ~"Hypoxemia, Low pH, proned", ph_715==0 & hypoxemia==1 & early_prone==1~"Hypoxemia, proned", ph_715==1 &   hypoxemia==0 & early_prone==1 ~"Low pH, proned",  ph_715==0 &  hypoxemia==0& early_prone==1~"Proned", ph_715==1 & hypoxemia==1 & early_prone==0 ~"Hypoxemia, Low pH", ph_715==0 & hypoxemia==1 & early_prone==0~"Hypoxemia", ph_715==1 &   hypoxemia==0 & early_prone==0 ~"Low pH",  ph_715==0 &  hypoxemia==0& early_prone==0~"None"), 
  risk_factors_meet_criteria2=case_when(ph_715==1 & hypoxemia==1 & dys_rr==1 ~"Hypoxemia, Low pH, Inc RR", ph_715==0 & hypoxemia==1 & dys_rr==1~"Hypoxemia, Inc RR", ph_715==1 &   hypoxemia==0 & dys_rr==1 ~"Low pH, Inc RR",  ph_715==0 &  hypoxemia==0 & dys_rr==1~"Inc RR", ph_715==1 & hypoxemia==1 & dys_rr==0 ~"Hypoxemia, Low pH", ph_715==0 & hypoxemia==1 & dys_rr==0 ~"Hypoxemia", ph_715==1 &   hypoxemia==0 & dys_rr==0 ~"Low pH",  ph_715==0 &  hypoxemia==0 & dys_rr==0~"None"), 
prone_48_cat = case_when(prone_48==1~"proned", prone_48==0~"unproned"),
paralytics_48_cat = case_when(any_paralytic_48==1~"paralyzed", any_paralytic_48==0~"not_paralyzed")
  ) |>
  collect()

rose_analytic_df <- rose_analytic_df |>
  mutate(covid_positive =case_when(sars_cov2_positive == '1'~1, is.na(sars_cov2_positive) | sars_cov2_positive=='0' ~0),
      enrollment_location_type = case_when(
      enrollment_location_type %in% c("general_icu", "mixed_cardiothoracic_icu") ~ "general_icu",
      enrollment_location_type == "cardiac_icu" ~ "cardiac_icu",
      enrollment_location_type %in% c("cardiothoracic_surgical_icu", "surgical_icu", "burn_icu") ~ "surgical_icu",
      enrollment_location_type %in% c("neuro_icu", "neurosurgical_icu", "mixed_neuro_icu") ~ "mixed_neuro_icu",
      enrollment_location_type == "medical_icu" ~ "medical_icu"),
      joint_prone_para6 = replace_na(fifelse(as.POSIXct(first_prone_time) <= as.POSIXct(paralytic_time) + hours(6), 1, 0), 0),
      para_to_prone = difftime(first_prone_time, paralytic_time, units = "hours"), 
      criteria_to_prone = difftime(first_prone_time, t_rose_first, units = "hours"))

earlyprone<- as.data.frame(table(rose_analytic_df$early_prone, rose_analytic_df$any_paralytic_48))
earlyprone$label = c("no paralytic or early prone", "early prone, no paralytic", "paralytic not early prone", "early prone on paralytic")
write.csv(earlyprone, file=paste0(project_location, '/project_output_UPLOAD/', site, '_early_proning_numbers.csv'))

earlyprone<- as.data.frame(table(rose_analytic_df$early_prone, rose_analytic_df$joint_prone_para6))
write.csv(earlyprone, file=paste0(project_location, '/project_output_UPLOAD/', site, '_joint_proning_numbers.csv'))

#variables at the time of paralytic initiation - it's initial paralytic time, if not started on paralytics will remove later. 
rose_analytic_df <- rose_analytic_df |> 
  mutate(initial_paralytic_type = case_when(paralytic_time==paralytic_start_time_c~"continuous", paralytic_time==paralytic_start_time_i_rose~"intermittent"),
  then_paralytic_c = case_when(initial_paralytic_type=="intermittent" & paralytic_start_time_c < (t_rose_first + hours(48))~ 1, initial_paralytic_type=="intermittent" & (is.na(paralytic_start_time_c) | paralytic_start_time_c >= (t_rose_first + hours(48)))~0),
  pfround_paralytic = round(lowest_ratio_paralytic),
  deep_rass_paralytic = case_when(min_rass12_paralytic< -3~1, min_rass12_paralytic>-4~0),
  deep_rass_max_paralytic = case_when(max_rass12_paralytic< -3~1, max_rass12_paralytic>-4~0),
  min_ph_paralytic = round(min_ph_paralytic, digits=2),
  ph_715_paralytic = case_when(is.na(min_ph_paralytic) | min_ph_paralytic >=7.15 ~0, min_ph_paralytic <7.15~1), 
  ph_72_paralytic = case_when(is.na(min_ph_paralytic) | min_ph_paralytic >=7.2 ~0, min_ph_paralytic <7.2~1), 
  dys_rr_paralytic = case_when(rr_diff_max_paralytic>15 ~1, rr_diff_max_paralytic <16 ~0), 
  dys_mv_paralytic = case_when(mv_obs_max_paralytic <16 ~0, mv_obs_max_paralytic >= 16~1), 
  agitated_rass_paralytic = fifelse(max_rass12_paralytic >1, 1,0), 
  hypoxemia_paralytic = fifelse(pfround_paralytic <100, 1, 0), 
  risk_factors_paralytic=case_when(joint_prone_para6==1 & hypoxemia_paralytic==1 & ph_715_paralytic==0 ~"Hypoxemia, Prone", joint_prone_para6==0 & hypoxemia_paralytic==1  & ph_715_paralytic==0~"Hypoxemia", joint_prone_para6==1 &   hypoxemia_paralytic==0 & ph_715_paralytic==0~"Prone",  joint_prone_para6==0 &  hypoxemia_paralytic==0 &  ph_715_paralytic==0~"None", joint_prone_para6==1 & hypoxemia_paralytic==1 & ph_715_paralytic==1 ~"Hypoxemia, Prone, Low pH", joint_prone_para6==0 & hypoxemia_paralytic==1 & ph_715_paralytic==1~"Hypoxemia, Low pH", joint_prone_para6==1 &   hypoxemia_paralytic==0 &   ph_715_paralytic==1~"Prone, Low pH",  joint_prone_para6==0 &  hypoxemia_paralytic==0  & ph_715_paralytic==1~"Low pH"),
  
  risk_factors_paralytic2=case_when(joint_prone_para6==1 & hypoxemia_paralytic==1 & ph_715_paralytic==0 & dys_rr_paralytic==1 ~"Hypoxemia, Prone, Inc RR", joint_prone_para6==0 & hypoxemia_paralytic==1  & ph_715_paralytic==0 & dys_rr_paralytic==1 ~"Hypoxemia, Inc RR", joint_prone_para6==1 &   hypoxemia_paralytic==0 & ph_715_paralytic==0 & dys_rr_paralytic==1 ~"Prone, Inc RR",  joint_prone_para6==0 &  hypoxemia_paralytic==0 &  ph_715_paralytic==0 & dys_rr_paralytic==1 ~"Inc RR", joint_prone_para6==1 & hypoxemia_paralytic==1 & ph_715_paralytic==1  & dys_rr_paralytic==1 ~"Hypoxemia, Prone, Low pH, Inc RR", joint_prone_para6==0 & hypoxemia_paralytic==1 & ph_715_paralytic==1  & dys_rr_paralytic==1 ~"Hypoxemia, Low pH, Inc RR", joint_prone_para6==1 &   hypoxemia_paralytic==0 &   ph_715_paralytic==1 & dys_rr_paralytic==1 ~"Prone, Low pH, Inc RR",  joint_prone_para6==0 &  hypoxemia_paralytic==0  & ph_715_paralytic==1 & dys_rr_paralytic==1 ~"Low pH, Inc RR", joint_prone_para6==1 & hypoxemia_paralytic==1 & ph_715_paralytic==0  & dys_rr_paralytic==0 ~"Hypoxemia, Prone", joint_prone_para6==0 & hypoxemia_paralytic==1  & ph_715_paralytic==0  & dys_rr_paralytic==0 ~"Hypoxemia", joint_prone_para6==1 &   hypoxemia_paralytic==0 & ph_715_paralytic==0  & dys_rr_paralytic==0 ~"Prone",  joint_prone_para6==0 &  hypoxemia_paralytic==0 &  ph_715_paralytic==0  & dys_rr_paralytic==0 ~"None", joint_prone_para6==1 & hypoxemia_paralytic==1 & ph_715_paralytic==1  & dys_rr_paralytic==0  ~"Hypoxemia, Prone, Low pH", joint_prone_para6==0 & hypoxemia_paralytic==1 & ph_715_paralytic==1  & dys_rr_paralytic==0 ~"Hypoxemia, Low pH", joint_prone_para6==1 &   hypoxemia_paralytic==0 &   ph_715_paralytic==1  & dys_rr_paralytic==0 ~"Prone, Low pH",  joint_prone_para6==0 &  hypoxemia_paralytic==0  & ph_715_paralytic==1  & dys_rr_paralytic==0 ~"Low pH")
  )   |>
  collect()

#AHRF cohort size overtime
ahrf_cohort<- read.csv(paste0(project_location, '/project_tables_DO_NOT_UPLOAD/ahrf_cohort_table.csv')) |>
  rename(year=Var1, 
         ahrf_cohort= Freq)

rose_analytic_df <- rose_analytic_df |>
  group_by(patient_id, encounter_block) |>
  mutate(year_criteria=min(year(t_rose_first))) |>
  ungroup()

rose <- as.data.frame(table(rose_analytic_df$year_criteria))
rose <- rose |>
  mutate(year=as.numeric(as.character(Var1))) |>
  filter(year<2026) |>
  rename(rose_eligible=Freq) |>
  select(-Var1) |>
  left_join(ahrf_cohort) |>
  mutate(proportion=rose_eligible/ahrf_cohort)

# Assign periods
rose$period <- ifelse(rose$year %in% 2018:2021, "2018-2021", "2022-2025")
write.csv(rose, file=paste0(project_location, '/project_output_UPLOAD/', site, '_ahrf_cohort_table.csv'))

# inclusions <- rose_analytic_df |>
#   filter(is.na(early_prone) | early_prone==0)
# 
# next_exclusion <- data.frame(
#   excluded_encounters = nrow(rose_analytic_df) - nrow(inclusions),
#     involved_patients = length(unique(rose_analytic_df$patient_id)) - length(unique(inclusions$patient_id)),
#   reason = "early prone"
# )

consort <- read.csv(paste0(project_location, '/project_output_UPLOAD/', site,'_consort.csv'))
consort <- consort[1:9, ]
#consort <- bind_rows(consort, next_exclusion)

#For patient_ids with more than one encounter block, select one at random
#rose_analytic_df <- rose_analytic_df |>
#  filter(is.na(early_prone) | early_prone==0) #remove those early proned before meeting criteria - > different etiology likely. 

inclusions <- rose_analytic_df |>
  filter(year(t_rose_first)<2026)

next_exclusion <- data.frame(
  excluded_encounters = nrow(rose_analytic_df) - nrow(inclusions),
    involved_patients = length(unique(rose_analytic_df$patient_id)) - length(unique(inclusions$patient_id)),
  reason = "2026 data"
)

consort <- bind_rows(consort, next_exclusion)

#Filter Out Those with t_enrollment in 2026
rose_analytic_df <- rose_analytic_df |>
  filter(year(t_rose_first)<2026)

duplicates <- nrow(rose_analytic_df)

rose_analytic_df <- rose_analytic_df |>
  group_by(patient_id) |>
  slice_sample(n=1) |>
  ungroup()

next_exclusion <- data.frame(
  excluded_encounters = duplicates - nrow(rose_analytic_df),
  reason = "duplicate patients"
)

consort <- bind_rows(consort, next_exclusion)

cat('At', site, length(unique(rose_analytic_df$patient_id)), 'met cohort eligibility based on ROSE criteria and are included in the final cohort. \n')

for (n in 4:nrow(consort)){
consort$encounters[n] = consort$encounters[n-1] - consort$excluded_encounters[n]
}

write_csv(consort, paste0(project_location, '/project_output_UPLOAD/', site,'_consort.csv'))
```


#Additional Cleaning of Analytic Dataset
#Includes Finalzing Covariates
```{r Define Study Months/Quarters}
#Further Define sex_category as female 1, male/other/unknown 0
rose_analytic_df <- rose_analytic_df |>
  mutate(female=fifelse(tolower(sex_category)=='female', 1, 0), 
         year=year(t_rose_first),
         calendar_month=month(t_rose_first)  
        ) |>
  arrange(year, calendar_month)

#Report Out Minimum and Maximum Times
cat('At', site, 'the first eligible patient was enrolled on', as.character(first(rose_analytic_df$t_rose_first)), 
    '\n and the last on', as.character(last(rose_analytic_df$t_rose_first)))

#Create a Study Month Data Frame to Merge to Create Study Month; Can Adjust ym() to accomadte desired period; for this analysis 2018 through 2025
study_month <- data.frame(start_date=seq(ym("201801"), ym("202512"), by= "months")) |>
  mutate(calendar_month=month(start_date)) |>
  mutate(year=year(start_date)) |>
  arrange(year, calendar_month) |>
  mutate(study_month=seq(1:n())) |>
  select(-start_date) |>
  mutate(study_quarter=ceiling(study_month/3))

#Now Merge to paralytics Analytic_DF
rose_analytic_df <- rose_analytic_df |>
  left_join(study_month) 
 
#Define the Pre-Specified Study Periods
#Jan 2018-Feb 2020 'Pre-ROSE/Pre-COVID', Mar 2020-Feb 2022 'Post-ROSE/COVID', Mar 2022-December 2025 'Post-ROSE/post-COVID'
rose_analytic_df <- rose_analytic_df |>
  filter(year<2026 & year>2017) |>
  mutate(study_period=fcase(
    study_month>=1 & study_month<27, 'Pre-ROSE/Pre-COVID',
    study_month>=27 & study_month<50, 'Post-ROSE/COVID',
    study_month>=50, 'Post-ROSE/Post-COVID'
  )) |>
  mutate(study_period_cat=factor(study_period,
                               levels = c("Pre-ROSE/Pre-COVID", "Post-ROSE/COVID", "Post-ROSE/Post-COVID"),
                               labels = c(0, 1, 2)))

#In this script we keep track of the minimum and maximum study month both for graphs and for the modelling
min_month <- min(rose_analytic_df$study_month, na.rm = T)
max_month <- max(rose_analytic_df$study_month, na.rm = T)
min_quarter <- min(rose_analytic_df$study_quarter, na.rm = T)
max_quarter <- max(rose_analytic_df$study_quarter, na.rm = T)

#Create 'site_type' vector that shows Which study periods are Included
site_type <- rose_analytic_df |>
  distinct(study_period) 
site_type <- paste(site_type$study_period, collapse = ",")

#Keep Track of the Number of Hospitals
n_hospitals <- length(unique(rose_analytic_df$hospital_id[!is.na(rose_analytic_df$hospital_id)]))

#Create a Few More Variables
rose_analytic_df <- rose_analytic_df |>
  mutate(admit_to_enrolled=as.duration(t_rose_first-final_admission_dttm)/dhours(1)) |>
  mutate(ett_to_enrolled=as.duration(t_rose_first-vent_episode_start)/dhours(1)) |>
  mutate(severe_ards=fifelse(first_rose_pf_all<100, 1, 0))

#If we can't confirm a positive or negative SARS-Cov2 test in the COVID or Post-COVID era, assumed negative
rose_analytic_df <- rose_analytic_df |>
 mutate(sars_cov2_positive=case_when(
   sars_cov2_positive==1~ 'Positive',
   study_month>=1 & study_month<27~ 'Pre-COVID',  #If less than March 2020, consider pre-covid
   sars_cov2_positive==0 | is.na(sars_cov2_positive)~ 'Negative',
 ))

n_periods <- length(unique(rose_analytic_df$study_period))

#Create a Histogram of Admissions Per Study Month by Hospital
#Create Month Labels - Will Use Study Specific Min and Max Months to Select The Right Grouping
month_labels <- c(
'Jan18', 'Feb18', 'Mar18','Apr18', 
'May18', 'Jun18', 'Jul18', 'Aug18',
'Sep18', 'Oct18', 'Nov18', 'Dec18',
'Jan19', 'Feb19', 'Mar19','Apr19', 
'May19', 'Jun19', 'Jul19', 'Aug19',
'Sep19', 'Oct19', 'Nov19', 'Dec19',
'Jan20', 'Feb20', 'Mar20','Apr20', 
'May20', 'Jun20', 'Jul20', 'Aug20',
'Sep20', 'Oct20', 'Nov20', 'Dec20',
'Jan21', 'Feb21', 'Mar21','Apr21', 
'May21', 'Jun21', 'Jul21', 'Aug21',
'Sep21', 'Oct21', 'Nov21', 'Dec21',
'Jan22', 'Feb22', 'Mar22','Apr22', 
'May22', 'Jun22', 'Jul22', 'Aug22',
'Sep22', 'Oct22', 'Nov22', 'Dec22',
'Jan23', 'Feb23', 'Mar23', 'Apr23', 
'May23', 'Jun23', 'Jul23', 'Aug23', 
'Sep23', 'Oct23', 'Nov23', 'Dec23',
'Jan24', 'Feb24', 'Mar24', 'Apr24', 
'May24', 'Jun24', 'Jul24', 'Aug24', 
'Sep24', 'Oct24', 'Nov24', 'Dec24', 
'Jan25', 'Feb25', 'Mar25', 'Apr25', 
'May25', 'Jun25', 'Jul25', 'Aug25', 
'Sep25', 'Oct25', 'Nov25', 'Dec25')

#Select the Relevant Months from This Vector Using the min_month, max_month
site_month_labels <- month_labels[min_month:max_month]
```
```{r Graph NMBA use}
#per period
paralytics_per_period <- rose_analytic_df |> 
  group_by(study_period) |>
  summarise(
    'site' = site,
    'n_hospitals' = n_hospitals,
    'n_patients' = n(),
    'n_paralytics_12_hr' = sum(any_paralytic_12),
    'paralytics_12_hr_percent' = mean(any_paralytic_12),
    'standard_error_12' = sqrt(mean(any_paralytic_12) * (1 - mean(any_paralytic_12)) / n()),
    'n_paralytics_24_hr' = sum(any_paralytic_24),
    'paralytics_24_hr_percent' = mean(any_paralytic_24),
    'standard_error_24' = sqrt(mean(any_paralytic_24) * (1 - mean(any_paralytic_24)) / n()),
    'n_paralytics_48_hr' = sum(any_paralytic_48),
    'paralytics_48_hr_percent' = mean(any_paralytic_48),
    'standard_error_48' = sqrt(mean(any_paralytic_48) * (1 - mean(any_paralytic_48)) / n()),
    'n_paralytics_72_hr' = sum(any_paralytic_72),
    'paralytics_72_hr_percent' = mean(any_paralytic_72),
    'standard_error_72' = sqrt(mean(any_paralytic_72) * (1 - mean(any_paralytic_72)) / n()),
    'n_paralytics_all' = sum(any_paralytic_ever),
    'paralytics_percent_all' = mean(any_paralytic_ever),
    'standard_error_all' = sqrt(mean(any_paralytic_ever) * (1 - mean(any_paralytic_ever)) / n())
  ) |>
  relocate(site, n_hospitals, .before = study_period)
write_csv(paralytics_per_period, paste0(project_location, '/project_output_UPLOAD/', site,'_paralytics_per_period.csv'))

#Repeat per period per hospital
#Create a Table of N of Patients and Number paralyzed Per Study period Per Hospital
paralytics_per_period_by_hospital <- rose_analytic_df |> 
  group_by(study_period, hospital_id) |> 
  filter(!is.na(hospital_id)) |>
  summarise(
    'site' = site,
    'n_hospitals' = n_hospitals,
    'n_patients' = n(),
    'n_paralytics_12_hr' = sum(any_paralytic_12),
    'paralytics_12_hr_percent' = mean(any_paralytic_12),
    'standard_error_12' = sqrt(mean(any_paralytic_12) * (1 - mean(any_paralytic_12)) / n()),
    'n_paralytics_24_hr' = sum(any_paralytic_24),
    'paralytics_24_hr_percent' = mean(any_paralytic_24),
    'standard_error_24' = sqrt(mean(any_paralytic_24) * (1 - mean(any_paralytic_24)) / n()),
    'n_paralytics_48_hr' = sum(any_paralytic_48),
    'paralytics_48_hr_percent' = mean(any_paralytic_48),
    'standard_error_48' = sqrt(mean(any_paralytic_48) * (1 - mean(any_paralytic_48)) / n()),
    'n_paralytics_72_hr' = sum(any_paralytic_72),
    'paralytics_72_hr_percent' = mean(any_paralytic_72),
    'standard_error_72' = sqrt(mean(any_paralytic_72) * (1 - mean(any_paralytic_72)) / n()),
    'n_paralytics_all' = sum(any_paralytic_ever),
    'paralytics_percent_all' = mean(any_paralytic_ever),
    'standard_error_all' = sqrt(mean(any_paralytic_ever) * (1 - mean(any_paralytic_ever)) / n())
   ) |>
  relocate(site, n_hospitals, .before = study_period)

write_csv(paralytics_per_period_by_hospital, paste0(project_location, '/project_output_UPLOAD/', site,'_paralytics_per_period_hospital.csv'))

#Repeat Per Study Quarter
paralytics_per_quarter <- rose_analytic_df |> 
  group_by(study_quarter) |>
  summarise(
    'site' = site,
    'n_hospitals' = n_hospitals,
    'n_patients' = n(),
    'sars_cov2_positive' = sum(sars_cov2_positive=='Positive', na.rm=T),
   'n_paralytics_12_hr' = sum(any_paralytic_12),
    'paralytics_12_hr_percent' = mean(any_paralytic_12),
    'standard_error_12' = sqrt(mean(any_paralytic_12) * (1 - mean(any_paralytic_12)) / n()),
    'n_paralytics_24_hr' = sum(any_paralytic_24),
    'paralytics_24_hr_percent' = mean(any_paralytic_24),
    'standard_error_24' = sqrt(mean(any_paralytic_24) * (1 - mean(any_paralytic_24)) / n()),
    'n_paralytics_48_hr' = sum(any_paralytic_48),
    'paralytics_48_hr_percent' = mean(any_paralytic_48),
    'standard_error_48' = sqrt(mean(any_paralytic_48) * (1 - mean(any_paralytic_48)) / n()),
    'n_paralytics_72_hr' = sum(any_paralytic_72),
    'paralytics_72_hr_percent' = mean(any_paralytic_72),
    'standard_error_72' = sqrt(mean(any_paralytic_72) * (1 - mean(any_paralytic_72)) / n()),
    'n_paralytics_all' = sum(any_paralytic_ever),
    'paralytics_percent_all' = mean(any_paralytic_ever),
    'standard_error_all' = sqrt(mean(any_paralytic_ever) * (1 - mean(any_paralytic_ever)) / n())
   ) |>
  relocate(site, n_hospitals, .before = study_quarter)

#Repeat per quarter per hospital
#Create a Table of N of Patients and Number paralyzed Per Study quarter Per Hospital
paralytics_per_quarter_by_hospital <- rose_analytic_df |> 
  group_by(study_quarter, hospital_id) |>
    filter(!is.na(hospital_id)) |>
  summarise(
    'site' = site,
    'n_hospitals' = n_hospitals,
    'n_patients' = n(),
    'n_paralytics_12_hr' = sum(any_paralytic_12),
    'paralytics_12_hr_percent' = mean(any_paralytic_12),
    'standard_error_12' = sqrt(mean(any_paralytic_12) * (1 - mean(any_paralytic_12)) / n()),
    'n_paralytics_24_hr' = sum(any_paralytic_24),
    'paralytics_24_hr_percent' = mean(any_paralytic_24),
    'standard_error_24' = sqrt(mean(any_paralytic_24) * (1 - mean(any_paralytic_24)) / n()),
    'n_paralytics_48_hr' = sum(any_paralytic_48),
    'paralytics_48_hr_percent' = mean(any_paralytic_48),
    'standard_error_48' = sqrt(mean(any_paralytic_48) * (1 - mean(any_paralytic_48)) / n()),
    'n_paralytics_72_hr' = sum(any_paralytic_72),
    'paralytics_72_hr_percent' = mean(any_paralytic_72),
    'standard_error_72' = sqrt(mean(any_paralytic_72) * (1 - mean(any_paralytic_72)) / n()),
    'n_paralytics_all' = sum(any_paralytic_ever),
    'paralytics_percent_all' = mean(any_paralytic_ever),
    'standard_error_all' = sqrt(mean(any_paralytic_ever) * (1 - mean(any_paralytic_ever)) / n())
   ) |>
  relocate(site, n_hospitals, .before = study_quarter)

#Repeat per quarter per hospital for unproned only
#Create a Table of N of Patients and Number paralyzed Per Study quarter Per Hospital
paralytics_per_quarter_by_hospital_unproned <- rose_analytic_df |> 
  group_by(study_quarter, hospital_id) |>
    filter(!is.na(hospital_id) & prone_48==0) |>
  summarise(
    'site' = site,
    'n_hospitals' = n_hospitals,
    'n_patients' = n(),
    'n_paralytics_12_hr' = sum(any_paralytic_12),
    'paralytics_12_hr_percent' = mean(any_paralytic_12),
    'standard_error_12' = sqrt(mean(any_paralytic_12) * (1 - mean(any_paralytic_12)) / n()),
    'n_paralytics_24_hr' = sum(any_paralytic_24),
    'paralytics_24_hr_percent' = mean(any_paralytic_24),
    'standard_error_24' = sqrt(mean(any_paralytic_24) * (1 - mean(any_paralytic_24)) / n()),
    'n_paralytics_48_hr' = sum(any_paralytic_48),
    'paralytics_48_hr_percent' = mean(any_paralytic_48),
    'standard_error_48' = sqrt(mean(any_paralytic_48) * (1 - mean(any_paralytic_48)) / n()),
    'n_paralytics_72_hr' = sum(any_paralytic_72),
    'paralytics_72_hr_percent' = mean(any_paralytic_72),
    'standard_error_72' = sqrt(mean(any_paralytic_72) * (1 - mean(any_paralytic_72)) / n()),
    'n_paralytics_all' = sum(any_paralytic_ever),
    'paralytics_percent_all' = mean(any_paralytic_ever),
    'standard_error_all' = sqrt(mean(any_paralytic_ever) * (1 - mean(any_paralytic_ever)) / n())
   ) |>
  relocate(site, n_hospitals, .before = study_quarter)

```

```{r Proning}
#Repeat Per Study Quarter
prone_per_quarter <- rose_analytic_df |> 
  group_by(study_quarter) |>
  summarise(
    'site' = site,
    'n_hospitals' = n_hospitals,
    'n_patients' = n(),
    'sars_cov2_positive' = sum(sars_cov2_positive=='Positive', na.rm=T),
    'n_prone_48_hr' = sum(prone_48),
    'prone_48_hr_percent' = mean(prone_48),
    'prone_standard_error_48' = sqrt(mean(prone_48) * (1 - mean(prone_48)) / n()),
    'n_prone_all' = sum(prone_all),
    'prone_percent_all' = mean(prone_all),
    'prone_standard_error_all' = sqrt(mean(prone_all) * (1 - mean(prone_all)) / n())
   ) |>
  relocate(site, n_hospitals, .before = study_quarter)

#Repeat Per Study Quarter per hospital
prone_per_quarter_by_hospital <- rose_analytic_df |> 
  group_by(study_quarter, hospital_id) |>
  filter(!is.na(hospital_id)) |>
  summarise(
    'site' = site,
    'n_hospitals' = n_hospitals,
    'n_patients' = n(),
    'sars_cov2_positive' = sum(sars_cov2_positive=='Positive', na.rm=T),
    'n_prone_48_hr' = sum(prone_48),
    'prone_48_hr_percent' = mean(prone_48),
    'prone_standard_error_48' = sqrt(mean(prone_48) * (1 - mean(prone_48)) / n()),
    'n_prone_all' = sum(prone_all),
    'prone_percent_all' = mean(prone_all),
    'prone_standard_error_all' = sqrt(mean(prone_all) * (1 - mean(prone_all)) / n())
   ) |>
  relocate(site, n_hospitals, .before = study_quarter)

```

```{r}
# #Prone and paralyzed Per Study Quarter
p_and_p_per_quarter <- rose_analytic_df |>
  group_by(study_quarter) |>
  summarise(
    'site' = site,
    'n_hospitals' = n_hospitals,
    'n_patients' = n(),
    'n_p_and_p_48_hr' = sum(p_and_p),
    'p_and_p_48_hr_percent' = mean(p_and_p),
    'p_and_p_standard_error_48' = sqrt(mean(p_and_p) * (1 - mean(p_and_p)) / n()),
      ) |>
  relocate(site, n_hospitals, .before = study_quarter)

# #Repeat Per Study Quarter - by hospital
p_and_p_per_quarter_by_hospital <- rose_analytic_df |>
  group_by(study_quarter, hospital_id) |>
  filter(!is.na(hospital_id)) |>
  summarise(
    'site' = site,
    'n_hospitals' = n_hospitals,
    'n_patients' = n(),
    'n_p_and_p_48_hr' = sum(p_and_p),
    'p_and_p_48_hr_percent' = mean(p_and_p),
    'p_and_p_standard_error_48' = sqrt(mean(p_and_p) * (1 - mean(p_and_p)) / n()),
      ) |>
  relocate(site, n_hospitals, .before = study_quarter)

# Per Study Quarter, excluding post-OR patients
paralytics_per_quarter_no_or <- rose_analytic_df |>
  filter(or_before_enrollment==0) |>
  group_by(study_quarter) |>
  summarise(
    'site' = site,
    'n_hospitals' = n_hospitals,
    'n_patients' = n(),
    'sars_cov2_positive' = sum(sars_cov2_positive=='Positive', na.rm=T),
   'n_paralytics_12_hr' = sum(any_paralytic_12),
    'paralytics_12_hr_percent' = mean(any_paralytic_12),
    'standard_error_12' = sqrt(mean(any_paralytic_12) * (1 - mean(any_paralytic_12)) / n()),
    'n_paralytics_24_hr' = sum(any_paralytic_24),
    'paralytics_24_hr_percent' = mean(any_paralytic_24),
    'standard_error_24' = sqrt(mean(any_paralytic_24) * (1 - mean(any_paralytic_24)) / n()),
    'n_paralytics_48_hr' = sum(any_paralytic_48),
    'paralytics_48_hr_percent' = mean(any_paralytic_48),
    'standard_error_48' = sqrt(mean(any_paralytic_48) * (1 - mean(any_paralytic_48)) / n()),
    'n_paralytics_72_hr' = sum(any_paralytic_72),
    'paralytics_72_hr_percent' = mean(any_paralytic_72),
    'standard_error_72' = sqrt(mean(any_paralytic_72) * (1 - mean(any_paralytic_72)) / n()),
    'n_paralytics_all' = sum(any_paralytic_ever),
    'paralytics_percent_all' = mean(any_paralytic_ever),
    'standard_error_all' = sqrt(mean(any_paralytic_ever) * (1 - mean(any_paralytic_ever)) / n())
   ) |>
  relocate(site, n_hospitals, .before = study_quarter)

#Repeat Per Study Quarter - no OR
prone_per_quarter_no_or <- rose_analytic_df |>
  filter(or_before_enrollment==0) |>
  group_by(study_quarter) |>
  summarise(
    'site' = site,
    'n_hospitals' = n_hospitals,
    'n_patients' = n(),
    'sars_cov2_positive' = sum(sars_cov2_positive=='Positive', na.rm=T),
    'n_prone_48_hr' = sum(prone_48),
    'prone_48_hr_percent' = mean(prone_48),
    'prone_standard_error_48' = sqrt(mean(prone_48) * (1 - mean(prone_48)) / n()),
    'n_prone_all' = sum(prone_all),
    'prone_percent_all' = mean(prone_all),
    'prone_standard_error_all' = sqrt(mean(prone_all) * (1 - mean(prone_all)) / n())
   ) |>
  relocate(site, n_hospitals, .before = study_quarter)

#paralyzed and prone no OR
p_and_p_per_quarter_no_or <- rose_analytic_df |>
  filter(or_before_enrollment==0) |>
  group_by(study_quarter) |>
  summarise(
    'site' = site,
    'n_hospitals' = n_hospitals,
    'n_patients' = n(),
    'n_p_and_p_48_hr' = sum(p_and_p),
    'p_and_p_48_hr_percent' = mean(p_and_p),
    'p_and_p_standard_error_48' = sqrt(mean(p_and_p) * (1 - mean(p_and_p)) / n()),
      ) |>
  relocate(site, n_hospitals, .before = study_quarter)

```

```{r Visualize Paralytics Use Over Time}
#Create Labels for Study Quarter
quarter_labels <- c(
'2018:1-3', '2018:4-6', '2018:7-9', '2018:10-12',
'2019:1-3', '2019:4-6', '2019:7-9', '2019:10-12',
'2020:1-3', '2020:4-6', '2020:7-9', '2020:10-12',
'2021:1-3', '2021:4-6', '2021:7-9', '2021:10-12',
'2022:1-3', '2022:4-6', '2022:7-9', '2022:10-12',
'2023:1-3', '2023:4-6', '2023:7-9', '2023:10-12',
'2024:1-3', '2024:4-6', '2024:7-9', '2024:10-12', 
'2025:1-3', '2025:4-6', '2025:7-9', '2025:10-12')
study_quarter_labels <- quarter_labels[min_quarter:max_quarter]

#Now Repeat for Month
#Label Every 3rd Month
tool <- seq(min_month, max_month, by=2)
new_month_labels <- site_month_labels[tool]
 
paralytics_per_quarter<- left_join(paralytics_per_quarter, prone_per_quarter)
paralytics_per_quarter<- left_join(paralytics_per_quarter, p_and_p_per_quarter)
write_csv(paralytics_per_quarter, paste0(project_location, '/project_output_UPLOAD/', site,'_paralytics_per_quarter.csv'))

paralytics_per_quarter_by_hospital<- left_join(paralytics_per_quarter_by_hospital , prone_per_quarter_by_hospital )
paralytics_per_quarter_by_hospital<- left_join(paralytics_per_quarter_by_hospital , p_and_p_per_quarter_by_hospital)
write_csv(paralytics_per_quarter_by_hospital, paste0(project_location, '/project_output_UPLOAD/', site,'_paralytics_per_quarter_by_hospital.csv'))

paralytics_per_quarter_no_or<- left_join(paralytics_per_quarter_no_or , prone_per_quarter_no_or)
paralytics_per_quarter_no_or<- left_join(paralytics_per_quarter_no_or , p_and_p_per_quarter_no_or)
write_csv(paralytics_per_quarter_no_or, paste0(project_location, '/project_output_UPLOAD/', site,'_paralytics_per_quarter_no_or.csv'))

#paralytics variability among unproned patients, nothing to join
write_csv(paralytics_per_quarter_by_hospital_unproned, paste0(project_location, '/project_output_UPLOAD/', site,'_paralytics_per_quarter_hospital_unproned.csv'))

#prone and paralytics per quarter - this is the main figure
base_plot <- ggplot(paralytics_per_quarter, aes(x=study_quarter)) +
  geom_line(aes(y=paralytics_48_hr_percent), color="blue") + 
  geom_line(aes(y=prone_48_hr_percent), color="red") + 
  geom_errorbar(aes(ymin = paralytics_48_hr_percent - 1.96 * standard_error_48, ymax = paralytics_48_hr_percent + 1.96 * standard_error_48), 
                width = 0.1, alpha = 0.5, color = 'grey') +
  geom_errorbar(aes(ymin = prone_48_hr_percent - 1.96 * prone_standard_error_48, ymax = prone_48_hr_percent + 1.96 * prone_standard_error_48), 
                width = 0.1, alpha = 0.5, color = 'grey') +
  geom_point(aes(y=paralytics_48_hr_percent)) +
  geom_point(aes(y=prone_48_hr_percent)) +
  scale_y_continuous(breaks=seq(0,1, by=0.1), 
                     labels = scales::percent, 
                     limits = c(0,1),
                     name = 'Paralyzed within 48 Hours of Meeting Study Criteria') +
  scale_x_continuous(breaks=seq(min_quarter, max_quarter, by=1),
                     labels = study_quarter_labels,
                     limits = c(min_quarter, max_quarter),
                     name = 'Year: Months') +
  theme_classic() + # theme_classic call
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) # custom x-axis text

#Now Add Annotations and Vertical Lines to Plot Based on What Data a Site Has Contributed
if (site_type == "Pre-ROSE/Pre-COVID,Post-ROSE/COVID,Post-ROSE/Post-COVID") {#If Site Has Full Study Period (2018-2025)
  extended <- base_plot +
    geom_vline(xintercept = 9, linetype = 2) +
    geom_vline(xintercept = 17, linetype = 2) +
    annotate("text", x=4.333333, y=0.95, label = 'Pre-ROSE \nPre-COVID') +
    annotate("text", x=13, y=0.95, label = 'Post-ROSE \nCOVID') +
    annotate("text", x=21.333333, y=0.95, label = 'Post-ROSE \nPost-COVID')
} else if (site_type == "Post-ROSE/COVID,Post-ROSE/Post-COVID") {
  extended <- base_plot + 
    geom_vline(xintercept = 9, linetype = 2) +
    geom_vline(xintercept = 17, linetype = 2) +
    annotate("text", x=13, y=0.95, label = 'Post-ROSE \nCOVID') +
    annotate("text", x=21.333333, y=0.95, label = 'Post-ROSE \nPost-COVID')
} else {
  extended <- base_plot
}

# Display the extended plot
extended
ggsave(paste0(site, '_prone_paralytics_by_quarter_48.pdf'),
       path = paste0(project_location, '/project_output_UPLOAD/'))

```

```{r Table 1 generation}
#Variables to Table 1
to_tab <- c(
  'any_paralytic_48',
  'age_at_admission',
  'female',
  'race_ethnicity',
  'bmi',
  'hospital_id',
  'year',
  'study_period',
  'sars_cov2_positive',
  'admit_to_enrolled', 
  'ett_to_enrolled',
  'or_before_enrollment',
  'first_rose_pf_all',
  'first_rose_fio2',
  'first_rose_peep',
  'severe_ards',
  'ards_icd_10',
  'first_rose_mode',
  'sofa_score',
  'nee_pressor_dose',
  'criteria',
  'deep_rass',
  'deep_rass_max',
  'min_rass12',
  'max_rass12',
  'agitated_rass',
  'rr_diff_max',
  'tv_cc_kg',
  'mv_obs_max',
  'plat_max',
  'compliance_min',
  'enrollment_location_type',
  'code_status_presume',
  'prone_48',
  'p_and_p',
  'prone_all',
  'early_prone',
  'ph_72',
  'dys_rr',
  'dys_mv',
  'ph_715', 
  'risk_factors_meet_criteria',
  'risk_factors_meet_criteria2',

  #paralytic variables
   'initial_paralytic_type', 
  'pfround_paralytic',
  'deep_rass_paralytic',
  'deep_rass_max_paralytic',
  'ph_715_paralytic', 
  'min_ph_paralytic',
  'ph_72_paralytic', 
  'dys_rr_paralytic', 
  'dys_mv_paralytic', 
  'agitated_rass_paralytic', 
  'hypoxemia_paralytic', 
  'risk_factors_paralytic',
  'risk_factors_paralytic2',

  'joint_prone_para6'
)

#Factor Variables
factors_tab <- c(
  'any_paralytic_48',
  'female',
  'race_ethnicity',
  'hospital_id',
  'year',
  'study_period',
  'sars_cov2_positive',
  'or_before_enrollment',
  'nee_pressor_dose',
  'severe_ards',
  'ards_icd_10',
  'first_rose_mode',
  'criteria',
  'deep_rass',
  'deep_rass_max',
  'ph_72',
  'agitated_rass',
  'enrollment_location_type',
  'code_status_presume',
  'prone_48',
  'p_and_p',
  'prone_all',
  'early_prone',
  'dys_rr',
  'dys_mv',
  'ph_715', 
  'initial_paralytic_type', 
  'deep_rass_paralytic',
  'deep_rass_max_paralytic',
  'ph_715_paralytic', 
  'ph_72_paralytic', 
  'dys_rr_paralytic', 
  'dys_mv_paralytic', 
  'agitated_rass_paralytic', 
  'hypoxemia_paralytic', 
  'risk_factors_meet_criteria',
  'risk_factors_meet_criteria2',
    'risk_factors_paralytic',
  'risk_factors_paralytic2',
  'joint_prone_para6'
  )

#Create a Traditional Table 1, stratified by paralytic use in 48h
tab1 <- suppressWarnings(CreateTableOne(vars = to_tab, strata="any_paralytic_48", data=rose_analytic_df, factorVars = factors_tab, addOverall = TRUE))
#print(tab1)
tab1_excel <- as.data.frame(print(tab1, printToggle = FALSE, missing = TRUE)) |>
  mutate(site = site) |>
  relocate(site, .before = Overall) |>
  rownames_to_column('characteristic') |>
  rename(percent_missing = Missing) |>
  select(-test)|>
  # Replace cells where the count (number before parenthesis) is < 10
  mutate(across(-c(characteristic, site, percent_missing, p), ~ {
    counts <- as.numeric(gsub("^\\s*([0-9]+)\\s*\\(.*", "\\1", .x))
    fifelse(!is.na(counts) & counts < 10 & counts > 0  & characteristic !="prone_48...1...." & characteristic !="early_prone...1...." & characteristic !="p_and_p...1...." & characteristic !="dys_rr...1...." & characteristic != "dys_mv...1...." & characteristic != "ph_715...1....", "<10"
            , .x)
    }))
write.csv(tab1_excel, file=paste0(project_location, '/project_output_UPLOAD/', site, '_Table1_by_Paralytics.csv'))
rm(tab1_excel)

#Create a Traditional Table 1, stratified by hospital
if(n_hospitals>1){
tab1 <- suppressWarnings(CreateTableOne(vars = to_tab, strata="hospital_id", data=rose_analytic_df, factorVars = factors_tab, addOverall = TRUE))
#print(tab1)
tab1_excel <- as.data.frame(print(tab1, printToggle = FALSE, missing = TRUE)) |>
  mutate(site = site) |>
  relocate(site, .before = Overall) |>
  rownames_to_column('characteristic') |>
  rename(percent_missing = Missing) |>
  select(-test)|>
  # Replace cells where the count (number before parenthesis) is < 10
  mutate(across(-c(characteristic, site, percent_missing, p), ~ {
    counts <- as.numeric(gsub("^\\s*([0-9]+)\\s*\\(.*", "\\1", .x))
    fifelse(!is.na(counts) & counts < 10 & counts > 0  & characteristic !="prone_48...1...." & characteristic !="early_prone...1...."& characteristic !="p_and_p...1...." & characteristic !="dys_rr...1...." & characteristic != "dys_mv...1...." & characteristic != "ph_715...1....", "<10"
            , .x)
    }))
write.csv(tab1_excel, file=paste0(project_location, '/project_output_UPLOAD/', site, '_Table1_by_hospital_id.csv'))
rm(tab1_excel)
} else {
tab1 <- suppressWarnings(CreateTableOne(vars = to_tab, data=rose_analytic_df, factorVars = factors_tab, addOverall = TRUE))
#print(tab1)
tab1_excel <- as.data.frame(print(tab1, printToggle = FALSE, missing = TRUE)) |>
  mutate(site = site) |>
  relocate(site, .before = Overall) |>
  rownames_to_column('characteristic') |>
  rename(percent_missing = Missing) |>
  # Replace cells where the count (number before parenthesis) is < 10
  mutate(across(-c(characteristic, site, percent_missing), ~ {
    counts <- as.numeric(gsub("^\\s*([0-9]+)\\s*\\(.*", "\\1", .x))
    fifelse(!is.na(counts) & counts < 10 & counts > 0  & characteristic !="prone_48...1...." & characteristic !="p_and_p...1...." & characteristic !="dys_rr...1...." & characteristic != "dys_mv...1...." & characteristic != "ph_715...1....", "<10"
            , .x)
    }))
write.csv(tab1_excel, file=paste0(project_location, '/project_output_UPLOAD/', site, '_Table1_by_hospital_id.csv'))
rm(tab1_excel)
}

#Now Create a Traditional Table 1, stratified by paralytic use in 48h and hospital
tab1 <- CreateTableOne(vars = to_tab, strata=c("any_paralytic_48", "hospital_id"), data=rose_analytic_df, factorVars = factors_tab, addOverall = TRUE) #if only 1 hospital then will run and drop hospital_id
tab1_excel <- as.data.frame(print(tab1, printToggle = FALSE, missing = TRUE)) |>
  mutate(site = site) |>
  relocate(site, .before = Overall) |>
  rownames_to_column('characteristic') |>
  rename(percent_missing = Missing) |>
  select(-test)|>
  # Replace cells where the count (number before parenthesis) is < 5
  mutate(across(-c(characteristic, site, percent_missing, p), ~ {
    counts <- as.numeric(gsub("^\\s*([0-9]+)\\s*\\(.*", "\\1", .x))
    fifelse(!is.na(counts) & counts < 10 & counts > 0 & characteristic !="prone_48...1...." & characteristic !="early_prone...1...."& characteristic !="p_and_p...1...." & characteristic !="dys_rr...1...." & characteristic != "dys_mv...1...." & characteristic != "ph_715...1...." & characteristic !="initial_paralytic_type...intermittent....", "<10", .x)
    }))
write.csv(tab1_excel, file=paste0(project_location, '/project_output_UPLOAD/', site, '_Table1_by_Paralytics_by_Hospital.csv'))
rm(tab1_excel)

#Now Table 1 stratified by study period
tab1 <- CreateTableOne(vars = to_tab, strata="study_period", data=rose_analytic_df, factorVars = factors_tab, addOverall = TRUE) 
tab1_excel <- as.data.frame(print(tab1, printToggle = FALSE, missing = TRUE)) |>
  mutate(site = site) |>
  relocate(site, .before = Overall) |>
  rownames_to_column('characteristic') |>
  rename(percent_missing = Missing) |>
  select(-test)|>
  # Replace cells where the count (number before parenthesis) is < 5
  mutate(across(-c(characteristic, site, percent_missing, p), ~ {
    counts <- as.numeric(gsub("^\\s*([0-9]+)\\s*\\(.*", "\\1", .x))
    fifelse(!is.na(counts) & counts < 10 & counts > 0& characteristic !="prone_48...1...." & characteristic !="early_prone...1...." & characteristic !="p_and_p...1...." & characteristic !="dys_rr...1...." & characteristic != "dys_mv...1...." & characteristic != "ph_715...1...." , "<10", .x)
    }))
write.csv(tab1_excel, file=paste0(project_location, '/project_output_UPLOAD/', site, '_Table1_by_Period.csv'))
rm(tab1_excel)

#Now Table 1 stratified by enrollment location
tab1 <- CreateTableOne(vars = to_tab, strata="enrollment_location_type", data=rose_analytic_df, factorVars = factors_tab, addOverall = TRUE) 
tab1_excel <- as.data.frame(print(tab1, printToggle = FALSE, missing = TRUE)) |>
  mutate(site = site) |>
  relocate(site, .before = Overall) |>
  rownames_to_column('characteristic') |>
  rename(percent_missing = Missing) |>
  select(-test)|>
  # Replace cells where the count (number before parenthesis) is < 5
  mutate(across(-c(characteristic, site, percent_missing, p), ~ {
    counts <- as.numeric(gsub("^\\s*([0-9]+)\\s*\\(.*", "\\1", .x))
    fifelse(!is.na(counts) & counts < 10 & counts > 0 & characteristic !="prone_48...1...." & characteristic !="early_prone...1...." & characteristic !="p_and_p...1...." & characteristic !="dys_rr...1...." & characteristic != "dys_mv...1...." & characteristic != "ph_715...1....", "<10", .x)
    }))
write.csv(tab1_excel, file=paste0(project_location, '/project_output_UPLOAD/', site, '_Table1_by_icu_type.csv'))
rm(tab1_excel)

#Now Table 1 stratified by prone_48
tab1 <- CreateTableOne(vars = to_tab, strata="prone_48", data=rose_analytic_df, factorVars = factors_tab, addOverall = TRUE) 
tab1_excel <- as.data.frame(print(tab1, printToggle = FALSE, missing = TRUE)) |>
  mutate(site = site) |>
  relocate(site, .before = Overall) |>
  rownames_to_column('characteristic') |>
  rename(percent_missing = Missing) |>
  select(-test)|>
  # Replace cells where the count (number before parenthesis) is < 5
  mutate(across(-c(characteristic, site, percent_missing, p), ~ {
    counts <- as.numeric(gsub("^\\s*([0-9]+)\\s*\\(.*", "\\1", .x))
    fifelse(!is.na(counts) & counts < 10 & counts > 0 & characteristic !="prone_48...1...." & characteristic !="early_prone...1...." & characteristic !="p_and_p...1...." & characteristic !="severe_ards...1...." & characteristic !="dys_rr...1...." & characteristic != "dys_mv...1...." & characteristic != "ph_715...1....", "<10", .x)
    }))
write.csv(tab1_excel, file=paste0(project_location, '/project_output_UPLOAD/', site, '_Table1_by_proning.csv'))
rm(tab1_excel)

#Now Table 1 stratified by prone_48 and paralytic
tab1 <- CreateTableOne(vars = to_tab, strata=c("prone_48", "any_paralytic_48"), data=rose_analytic_df, factorVars = factors_tab, addOverall = TRUE) 
tab1_excel <- as.data.frame(print(tab1, printToggle = FALSE, missing = TRUE)) |>
  mutate(site = site) |>
  relocate(site, .before = Overall) |>
  rownames_to_column('characteristic') |>
  rename(percent_missing = Missing) |>
  select(-test)|>
  # Replace cells where the count (number before parenthesis) is < 5
  mutate(across(-c(characteristic, site, percent_missing, p), ~ {
    counts <- as.numeric(gsub("^\\s*([0-9]+)\\s*\\(.*", "\\1", .x))
    fifelse(!is.na(counts) & counts < 10 & counts > 0 & characteristic !="prone_48...1...." & characteristic !="early_prone...1...." & characteristic !="p_and_p...1...." & characteristic !="severe_ards...1...." & characteristic !="dys_rr...1...." & characteristic != "dys_mv...1...." & characteristic != "ph_715...1....", "<10", .x)
    }))
write.csv(tab1_excel, file=paste0(project_location, '/project_output_UPLOAD/', site, '_Table1_by_proning_paralytic.csv'))
rm(tab1_excel)

#Now Table 1 stratified by prone_48 and paralytic - unproned
tab1 <- CreateTableOne(vars = to_tab, strata=c("any_paralytic_48"), data=rose_analytic_df %>% filter(prone_48==0), factorVars = factors_tab, addOverall = TRUE) 
tab1_excel <- as.data.frame(print(tab1, printToggle = FALSE, missing = TRUE)) |>
  mutate(site = site) |>
  relocate(site, .before = Overall) |>
  rownames_to_column('characteristic') |>
  rename(percent_missing = Missing) |>
  select(-test)|>
  # Replace cells where the count (number before parenthesis) is < 5
  mutate(across(-c(characteristic, site, percent_missing, p), ~ {
    counts <- as.numeric(gsub("^\\s*([0-9]+)\\s*\\(.*", "\\1", .x))
    fifelse(!is.na(counts) & counts < 10 & counts > 0 & characteristic !="prone_48...1...."& characteristic !="early_prone...1...."  & characteristic !="p_and_p...1...." & characteristic !="severe_ards...1...." & characteristic !="dys_rr...1...." & characteristic != "dys_mv...1...." & characteristic != "ph_715...1....", "<10", .x)
    }))
write.csv(tab1_excel, file=paste0(project_location, '/project_output_UPLOAD/', site, '_Table1_by_paralytic_unproned.csv'))
rm(tab1_excel)
```

```{r Counts table to determine which hospitals to exclude from meta analysis d/t small counts}
#look at study periods
if(n_periods==3){
all_sp_prone <- rose_analytic_df %>%
  count(hospital_id, study_period, prone_48_cat, paralytics_48_cat) %>%
  arrange(hospital_id, study_period, prone_48_cat, paralytics_48_cat)
all_sp <- rose_analytic_df %>%
  count(hospital_id, study_period, paralytics_48_cat) %>%
  arrange(hospital_id, study_period, paralytics_48_cat)
or_sp_prone <- rose_analytic_df %>%
  filter(or_before_enrollment == 0) %>%
  count(hospital_id, study_period, prone_48_cat, paralytics_48_cat) %>%
  arrange(hospital_id, study_period, prone_48_cat, paralytics_48_cat)
or_sp <- rose_analytic_df %>%
  filter(or_before_enrollment == 0) %>%
  count(hospital_id, study_period, paralytics_48_cat) %>%
  arrange(hospital_id, study_period, paralytics_48_cat)
covid_sp_prone <- rose_analytic_df %>%
  filter(covid_positive == 0) %>%
  count(hospital_id, study_period, prone_48_cat, paralytics_48_cat) %>%
  arrange(hospital_id, study_period, prone_48_cat, paralytics_48_cat)
covid_sp <- rose_analytic_df %>%
  filter(covid_positive == 0) %>%
  count(hospital_id, study_period, paralytics_48_cat) %>%
  arrange(hospital_id, study_period, paralytics_48_cat)
ards_sp_prone <- rose_analytic_df %>%
  filter(ards_icd_10 == 1) %>%
  count(hospital_id, study_period, prone_48_cat, paralytics_48_cat) %>%
  arrange(hospital_id, study_period, prone_48_cat, paralytics_48_cat)
ards_sp <- rose_analytic_df %>%
  filter(ards_icd_10 == 1) %>%
  count(hospital_id, study_period, paralytics_48_cat) %>%
  arrange(hospital_id, study_period, paralytics_48_cat)
severe_sp_prone <- rose_analytic_df %>%
  filter(severe_ards == 1) %>%
  count(hospital_id, study_period, prone_48_cat, paralytics_48_cat) %>%
  arrange(hospital_id, study_period, prone_48_cat, paralytics_48_cat)
severe_sp <- rose_analytic_df %>%
  filter(severe_ards == 1) %>%
  count(hospital_id, study_period, paralytics_48_cat) %>%
  arrange(hospital_id, study_period, paralytics_48_cat)
} 

#all sites
all_prone <- rose_analytic_df %>%
  count(hospital_id, prone_48_cat, paralytics_48_cat) %>%
  arrange(hospital_id, prone_48_cat, paralytics_48_cat)
ph <- rose_analytic_df %>%
  filter(prone_48 == 0) %>%
  count(hospital_id, ph_715, paralytics_48_cat) %>%
  arrange(hospital_id, ph_715, paralytics_48_cat)
rr <- rose_analytic_df %>%
  filter(prone_48 == 0) %>%
  count(hospital_id, dys_rr, paralytics_48_cat) %>%
  arrange(hospital_id, dys_rr, paralytics_48_cat)
mv <- rose_analytic_df %>%
  filter(prone_48 == 0) %>%
  count(hospital_id, dys_mv, paralytics_48_cat) %>%
  arrange(hospital_id, dys_mv, paralytics_48_cat)
or_prone <- rose_analytic_df %>%
  filter(or_before_enrollment == 0) %>%
  count(hospital_id, prone_48_cat, paralytics_48_cat) %>%
  arrange(hospital_id, prone_48_cat, paralytics_48_cat)
covid_prone <- rose_analytic_df %>%
  filter(covid_positive == 0) %>%
  count(hospital_id, prone_48_cat, paralytics_48_cat) %>%
  arrange(hospital_id, prone_48_cat, paralytics_48_cat)
ards_prone <- rose_analytic_df %>%
  filter(ards_icd_10 == 1) %>%
  count(hospital_id, prone_48_cat, paralytics_48_cat) %>%
  arrange(hospital_id, prone_48_cat, paralytics_48_cat)
severe_prone <- rose_analytic_df %>%
  filter(severe_ards == 1) %>%
  count(hospital_id, prone_48_cat, paralytics_48_cat) %>%
  arrange(hospital_id, prone_48_cat, paralytics_48_cat)
icu <- rose_analytic_df %>%
  count(enrollment_location_type, prone_48_cat, paralytics_48_cat) %>%
  arrange(enrollment_location_type, prone_48_cat, paralytics_48_cat)


#Summary Table With All Models
if(n_periods==3){
  main_table <- bind_rows(
    data.frame(site = c("whole - prone")),
    all_prone,
    data.frame(site = c("whole - SP")),
    all_sp,
    data.frame(site = c("Whole both")),
    all_sp_prone,
    data.frame(site = c("No_or - prone")),
    or_prone,
    data.frame(site = c("No_or - SP")),
    or_sp,
    data.frame(site = c("No_or both")),
    or_sp_prone,
    data.frame(site = c("No_covid - prone")),
    covid_prone,
    data.frame(site = c("No_covid - SP")),
    covid_sp,
    data.frame(site = c("No_covid both")),
    covid_sp_prone,
    data.frame(site = c("ards - prone")),
    ards_prone,
    data.frame(site = c("ards - SP")),
    ards_sp,
    data.frame(site = c("ards both")),
    all_sp_prone,
    data.frame(site = c("severe - prone")),
    severe_prone,
    data.frame(site = c("severe - SP")),
    severe_sp,
    data.frame(site = c("severe both")),
    severe_sp_prone,
    data.frame(site = c("icu")),
    icu,
    data.frame(site = c("ph")),
    ph,
    data.frame(site = c("rr")),
    rr,
    data.frame(site = c("mv")),
    mv
)
} else{
  main_table <- bind_rows(
    data.frame(site = c("whole - prone")),
    all_prone,
    data.frame(site = c("No_or - prone")),
    or_prone,
        data.frame(site = c("No_covid - prone")),
    covid_prone,
        data.frame(site = c("ards - prone")),
    ards_prone,
        data.frame(site = c("severe - prone")),
    severe_prone,
    data.frame(site = c("icu")),
    icu,
    data.frame(site = c("ph")),
    ph,
    data.frame(site = c("rr")),
    rr,
    data.frame(site = c("mv")),
    mv
    )
}
# Write the table to a CSV file
write.csv(main_table, paste0(project_location, '/project_output_UPLOAD/', site, '_ma_counts_by_period_hospital_paralytic.csv'))

```

```{r alluvival plot}
#alluvial plot data
alluvial_data_long <- rose_analytic_df |>
  filter(!is.na(risk_factors_meet_criteria)  & !is.na(risk_factors_paralytic)) |>
  count(risk_factors_meet_criteria, risk_factors_paralytic) |>
  gather_set_data(1:2)  # converts to long format for ggforce

write_csv(alluvial_data_long, paste0(project_location, '/project_output_UPLOAD/', site,'_alluvial_numbers.csv'))

alluvial_data_long2 <- rose_analytic_df |>
  filter(!is.na(risk_factors_meet_criteria2)  & !is.na(risk_factors_paralytic2)) |>
  count(risk_factors_meet_criteria2, risk_factors_paralytic2) |>
  gather_set_data(1:2)  # converts to long format for ggforce

write_csv(alluvial_data_long2, paste0(project_location, '/project_output_UPLOAD/', site,'_alluvial_numbers_rr.csv'))


alluvial_data_long <- alluvial_data_long |>
  filter(n>10)

alluvial <- ggplot(alluvial_data_long, aes(x, id = id, split = y, value = n)) +
  geom_parallel_sets(aes(fill = risk_factors_meet_criteria), alpha = 0.7) +
  geom_parallel_sets_axes(axis.width = 0.15, fill = "grey80") +
  geom_parallel_sets_labels(colour = "black", size = 3, angle = 0,
                            hjust = 0.5 ) +
  scale_fill_brewer(palette = "Set2") +
  labs(
    title = "Flow from Risk Factor Criteria to Paralytic Agent",
    y = "Number of Patients",
    fill = "Risk Factor Criteria"
  ) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    plot.title = element_text(hjust = 0.5, face = "bold"),
    axis.text.y = element_blank()
  )

alluvial
ggsave(paste0(site, '_alluvial.pdf'),
       path = paste0(project_location, '/project_output_UPLOAD/'))

```

```{r Paralytics and Patient Outcomes in Table Form}
rose_analytic_df <- rose_analytic_df |>
  mutate(study_period2 = study_period,
  hospital_id2 = as.factor(as.character(hospital_id)),
  any_paralytic_482 = any_paralytic_48,
  para_to_prone_numeric = as.numeric(as.character(para_to_prone, units = "hours"))
  )


to_tab <- c(
  'any_paralytic_12',
  'any_paralytic_24',
  'any_paralytic_48',
  'any_paralytic_72',
  'any_paralytic_ever',
  'in_hosp_death',
  'death_or_hospice', 
  'criteria_to_paralytic',
  'ett_to_paralytic',
  'first_rose_pf_all',
  'pfround_paralytic',
  'prone_48',
  'early_prone',
  'min_ph',
  'para_to_prone_numeric',
   # 'total_continuous_para_hours_prior',
  'total_continuous_para_hours_post',
  'total_continuous_para_hours_all',
  'total_continuous_para_hours_48h', 
  'study_period2',
  'hospital_id2',
  'any_paralytic_482',
  'continous_paralytic_given',
  'initial_paralytic_type'

)

#Factor Variables
factors_tab <- c(
  'study_period2',
  'hospital_id2',
  'any_paralytic_482',
  'any_paralytic_12',
  'any_paralytic_24',
  'any_paralytic_48',
  'any_paralytic_72',
  'any_paralytic_ever',
  'in_hosp_death',
  'death_or_hospice',
  'prone_48',
  'early_prone',
  'continous_paralytic_given',
  'initial_paralytic_type'
)

rose_analytic_df <- rose_analytic_df |>
  mutate(across(all_of(factors_tab), as.factor))

# Get all continuous variables (those not in factors_tab)
continuous_vars <- setdiff(to_tab, factors_tab)

permitted <- c("n", "any_paralytic_12 = 1 (%)", "any_paralytic_24 = 1 (%)", "any_paralytic_48 = 1 (%)", "any_paralytic_72 = 1 (%)", "any_paralytic_ever = 1 (%)", "in_hosp_death = 1 (%)",  "death_or_hospice = 1 (%)"  , "criteria_to_paralytic (mean (SD))", "ett_to_paralytic (mean (SD))" , "first_rose_pf_all (mean (SD))" , "pfround_paralytic (mean (SD))",  "prone_48 = 1 (%)"  , "early_prone = 1 (%)"  , "min_ph (mean (SD))" , "para_to_prone_numeric (mean (SD))" , "total_continuous_para_hours_post (mean (SD))" , "total_continuous_para_hours_all (mean (SD))" ,  "total_continuous_para_hours_48h (mean (SD))" , "study_period2 (%)" , "   Post-ROSE/COVID" , "   Post-ROSE/Post-COVID" , "   Pre-ROSE/Pre-COVID" ,    "any_paralytic_482 = 1 (%)" , "continous_paralytic_given (%)"  , "   atracurium"  , "   cisatracurium"  , "   rocuronium"    ,  "   vecuronium"   , "initial_paralytic_type = intermittent (%)",  "criteria_to_paralytic (median [IQR])", "ett_to_paralytic (median [IQR])", "first_rose_pf_all (median [IQR])", "pfround_paralytic (median [IQR])" , "min_ph (median [IQR])", "para_to_prone_numeric (median [IQR])" , "total_continuous_para_hours_post (median [IQR])", "total_continuous_para_hours_all (median [IQR])" , "total_continuous_para_hours_48h (median [IQR])")
permitted<- c(permitted, hospital_names)

# Create Table 2, stratified by study period (or unstratified if only one period)
if (n_periods >1) {
  tab2 <- CreateTableOne(vars = to_tab, strata = "study_period", data = rose_analytic_df, factorVars = factors_tab, addOverall = TRUE)
  
  tab2_excel <- as.data.frame(print(tab2, printToggle = FALSE, missing = TRUE)) |>
    mutate(site = site) |>
    relocate(site, .before = Overall) |>
    rownames_to_column('characteristic') |>
    rename(percent_missing = Missing) |>
    select(-test)
  tab2_excel<- tab2_excel |>
    filter(characteristic %in% permitted)  
  
  write.csv(tab2_excel, file=paste0(project_location, '/project_output_UPLOAD/', site, '_Table_paralytics_Outcomes_Period.csv'))
} 
  
#Now Create Table 2, One Stratified by paralytic use
tab2 <- suppressWarnings(CreateTableOne(vars = to_tab, strata="any_paralytic_48", data=rose_analytic_df, factorVars = factors_tab, addOverall = TRUE))
#print(tab2)
tab2_excel <- as.data.frame(print(tab2, printToggle = FALSE, missing = TRUE)) |>
  mutate(site = site) |>
  relocate(site, .before = Overall) |>
  rownames_to_column('characteristic') |>
  rename(percent_missing = Missing) |>
  select(-test)

tab2_excel<- tab2_excel |>
    filter(characteristic %in% permitted)  

write.csv(tab2_excel, file=paste0(project_location, '/project_output_UPLOAD/', site, '_Table_paralytics_Outcomes_Paralytics.csv'))

 # Table with Median [IQR]
  tab2_median <- as.data.frame(print(tab2, nonnormal = continuous_vars, printToggle = FALSE, missing = TRUE)) |>
  rownames_to_column('characteristic') |>
  rename(percent_missing = Missing) |>
  select(-test)
  
  tab2_median<- tab2_median |>
    filter(characteristic %in% permitted)  
  
  write.csv(tab2_median, file=paste0(project_location, '/project_output_UPLOAD/', site, '_Table_paralytics_Outcomes_Paralytics_median.csv'))

#Now Create a Table 2, Stratified by Hospital
if (n_hospitals>1) {
tab2 <- suppressWarnings(CreateTableOne(vars = to_tab, strata="hospital_id", data=rose_analytic_df, factorVars = factors_tab, addOverall = TRUE))
#print(tab2)
tab2_excel <- as.data.frame(print(tab2, printToggle = FALSE, missing = TRUE)) |>
  mutate(site = site) |>
  relocate(site, .before = Overall) |>
  rownames_to_column('characteristic') |>
  rename(percent_missing = Missing) |>
  select(-test)
} else {
tab2 <- suppressWarnings(CreateTableOne(vars = to_tab, data=rose_analytic_df, factorVars = factors_tab, addOverall = TRUE))
#print(tab2)
tab2_excel <- as.data.frame(print(tab2, printToggle = FALSE, missing = TRUE)) |>
  mutate(site = site) |>
  relocate(site, .before = Overall) |>
  rownames_to_column('characteristic') |>
  rename(percent_missing = Missing) 
}
  tab2_excel<- tab2_excel |>
    filter(characteristic %in% permitted)  
write.csv(tab2_excel, file=paste0(project_location, '/project_output_UPLOAD/', site, '_Table_paralytics_Outcomes_by_Hospital.csv'))


permitted_gt <- c("any_paralytic_12", "0", "1", "any_paralytic_24", "any_paralytic_72", "any_paralytic_ever", "in_hosp_death", "Unknown", "death_or_hospice"  , "criteria_to_paralytic", "ett_to_paralytic" , "first_rose_pf_all" , "pfround_paralytic",  "prone_48"  , "early_prone"  , "min_ph" , "para_to_prone_numeric" , "total_continuous_para_hours_post" , "total_continuous_para_hours_all" ,  "total_continuous_para_hours_48h" , "study_period2" , "Post-ROSE/COVID" , "Post-ROSE/Post-COVID" , "Pre-ROSE/Pre-COVID" ,    "any_paralytic_482" , "continous_paralytic_given"  , "atracurium"  , "cisatracurium"  , "rocuronium"    ,  "vecuronium"   , "initial_paralytic_type",  "criteria_to_paralytic", "ett_to_paralytic", "first_rose_pf_all", "pfround_paralytic" , "min_ph", "para_to_prone_numeric" , "total_continuous_para_hours_post", "total_continuous_para_hours_all" , "total_continuous_para_hours_48h", "initial_paralytic_type", "continuous", "intermittent", "hospital_id2")
permitted_gt<- c(permitted_gt, hospital_names)


#multiple factors for stratification to have interpretable median values for paralytic timing
#study period and paralytic use
if (n_periods >1) {
  tab2_gt <- rose_analytic_df |>
  select(all_of(to_tab), study_period, any_paralytic_48) |>
  tbl_strata(
    strata = study_period,
    .tbl_fun = ~ .x |>
      tbl_summary(
        by = any_paralytic_48,
        statistic = list(all_continuous() ~ "{mean} ({sd})"),
        missing = "ifany"))

tab2_gt <- as_tibble(tab2_gt)

  tab2_gt<- tab2_gt |>
    filter(`**Characteristic**` %in% permitted_gt)   

write.csv(tab2_gt, file=paste0(project_location, '/project_output_UPLOAD/', site, '_Table_paralytics_Outcomes_by_paralytics_period.csv'))

#median
  tab2_gt <- rose_analytic_df |>
  select(all_of(to_tab), study_period, any_paralytic_48) |>
  tbl_strata(
    strata = study_period,
    .tbl_fun = ~ .x |>
      tbl_summary(
        by = any_paralytic_48,
        statistic = list(all_continuous() ~ "{median} [{p25}, {p75}]"),
        missing = "ifany"))

tab2_gt <- as_tibble(tab2_gt)

  tab2_gt<- tab2_gt |>
    filter(`**Characteristic**` %in% permitted_gt)   

write.csv(tab2_gt, file=paste0(project_location, '/project_output_UPLOAD/', site, '_Table_paralytics_Outcomes_by_paralytics_period_median.csv'))

}

#multiple factors for stratification to have interpretable median values for paralytic timing
if (n_periods >1) {
  tab2_gt <- rose_analytic_df |>
  select(all_of(to_tab), study_period, any_paralytic_48) |>
  tbl_strata(
    strata = study_period,
    .tbl_fun = ~ .x |>
      tbl_summary(
        by = any_paralytic_48,
        statistic = list(all_continuous() ~ "{mean} ({sd})"),
        missing = "ifany"))

tab2_gt <- as_tibble(tab2_gt)

  tab2_gt<- tab2_gt |>
    filter(`**Characteristic**` %in% permitted_gt)   
  
write.csv(tab2_gt, file=paste0(project_location, '/project_output_UPLOAD/', site, '_Table_paralytics_Outcomes_by_paralytics_period.csv'))

#median
  tab2_gt <- rose_analytic_df |>
  select(all_of(to_tab), study_period, any_paralytic_48) |>
  tbl_strata(
    strata = study_period,
    .tbl_fun = ~ .x |>
      tbl_summary(
        by = any_paralytic_48,
        statistic = list(all_continuous() ~ "{median} [{p25}, {p75}]"),
        missing = "ifany"))

tab2_gt <- as_tibble(tab2_gt)

  tab2_gt<- tab2_gt |>
    filter(`**Characteristic**` %in% permitted_gt)   
  
write.csv(tab2_gt, file=paste0(project_location, '/project_output_UPLOAD/', site, '_Table_paralytics_Outcomes_by_paralytics_period_median.csv'))

}

#stratified by hospital and paralytic use
  tab2_gt <- rose_analytic_df |>
  select(all_of(to_tab), hospital_id, any_paralytic_48) |>
      filter(!is.na(hospital_id)) |>
  tbl_strata(
    strata = hospital_id,
    .tbl_fun = ~ .x |>
      tbl_summary(
        by = any_paralytic_48,
        statistic = list(all_continuous() ~ "{mean} ({sd})"),
        missing = "ifany"))

tab2_gt <- as_tibble(tab2_gt)

  tab2_gt<- tab2_gt |>
    filter(`**Characteristic**` %in% permitted_gt)   
  
write.csv(tab2_gt, file=paste0(project_location, '/project_output_UPLOAD/', site, '_Table_paralytics_Outcomes_by_paralytics_hospital.csv'))

#median
  tab2_gt <- rose_analytic_df |>
  select(all_of(to_tab), hospital_id, any_paralytic_48) |>
      filter(!is.na(hospital_id)) |>
  tbl_strata(
    strata = hospital_id,
    .tbl_fun = ~ .x |>
      tbl_summary(
        by = any_paralytic_48,
        statistic = list(all_continuous() ~ "{median} [{p25}, {p75}]"),
        missing = "ifany"))

tab2_gt <- as_tibble(tab2_gt)

  tab2_gt<- tab2_gt |>
    filter(`**Characteristic**` %in% permitted_gt)   
  
write.csv(tab2_gt, file=paste0(project_location, '/project_output_UPLOAD/', site, '_Table_paralytics_Outcomes_by_paralytics_hospital_median.csv'))


#stratified by hospital and paralytic use, unproned
  tab2_gt <- rose_analytic_df |>
  select(all_of(to_tab), hospital_id, any_paralytic_48) |>
      filter(!is.na(hospital_id) & prone_48==0) |>
  tbl_strata(
    strata = hospital_id,
    .tbl_fun = ~ .x |>
      tbl_summary(
        by = any_paralytic_48,
        statistic = list(all_continuous() ~ "{mean} ({sd})"),
        missing = "ifany"))

tab2_gt <- as_tibble(tab2_gt)

  tab2_gt<- tab2_gt |>
    filter(`**Characteristic**` %in% permitted_gt)   
  
  write.csv(tab2_gt, file=paste0(project_location, '/project_output_UPLOAD/', site, '_Table_paralytics_Outcomes_by_paralytics_hospital_unproned.csv'))

#median - among unproned patients
  tab2_gt <- rose_analytic_df |>
          filter(prone_48==0) |>
  select(all_of(to_tab), hospital_id, any_paralytic_48) |>
      filter(!is.na(hospital_id)) |>
  tbl_strata(
    strata = hospital_id,
    .tbl_fun = ~ .x |>
      tbl_summary(
        by = any_paralytic_48,
        statistic = list(all_continuous() ~ "{median} [{p25}, {p75}]"),
        missing = "ifany"))

tab2_gt <- as_tibble(tab2_gt)

  tab2_gt<- tab2_gt |>
    filter(`**Characteristic**` %in% permitted_gt)   
  
  write.csv(tab2_gt, file=paste0(project_location, '/project_output_UPLOAD/', site, '_Table_paralytics_Outcomes_by_paralytics_hospital_median_unproned.csv'))


```


```{r Function to Summarise Logistic Regression Models}
model_summary_table <- function(model) {
 
#Uses Fixed Effects for Hospital in Sites with > 1 Hospital (and clustered standard errors)  
if (n_hospitals>1) {
  #Cluster Robust Standard Errors Using LM Test
  coef_table <- coeftest(model, 
                         vcovCL(model, cluster = model.frame(model)$hospital_id)) 
  # Cluster-robust covariance matrix
  clustered_se <- vcovCL(model, cluster = model.frame(model)$hospital_id)
  #Compute confidence intervals manually using the clustered SE
  conf_int <- coefci(model, vcov. = clustered_se)
}  else {
  coef_table <- coeftest(model)
  conf_int <- coefci(model)
}
 model_table <- data.frame(
  'site' = site,
  'n_observations' = nobs(model),
  'term' = rownames(coef_table),
  'estimate' = coef_table[, "Estimate"],
  'std_error' = coef_table[, "Std. Error"],
  'p_value' = coef_table[, "Pr(>|z|)"],
  'odds_ratio' = round(exp(coef_table[, "Estimate"]), 3),  # Exponentiated coefficients as Odds Ratios
  'lower_bound' = exp(conf_int[, 1]),  # Lower bound of CI from coefci()
  'upper_bound' = exp(conf_int[, 2])   # Upper bound of CI from coefci()
)
model_table <- model_table |>
  mutate(confidence_interval=paste0(round(lower_bound, 3), ' - ', round(upper_bound, 3))) |>
  mutate(n_hospitals=n_hospitals) |>
  relocate(confidence_interval, .before = lower_bound) |>
  relocate(n_hospitals, .after = n_observations) 
  rownames(model_table) <- NULL
return(model_table)
}

rose_analytic_df$any_paralytic_48<- as.numeric(as.character(rose_analytic_df$any_paralytic_48))

```


```{r Logistic Regression}
#To Aid In Intrepretability Plan to Scale Each of The Continuous Variables
#Will Use Global Mean from Preliminary Data to Center Each Variable and then Scale by Reasonable Delta
rose_analytic_df <- rose_analytic_df |>
  mutate(
    age_scale=(age_at_admission-60)/10,
    bmi_scale=(bmi-30)/5,
    first_rose_pf_all_scale=(first_rose_pf_all-100)/10,
    first_rose_fio2_scale=(first_rose_fio2-0.8)/.1 ,
    first_rose_peep_scale = (first_rose_peep - 10),
    compliance_scale = (compliance_estimate_min - 30)/5,
    compliance_scale_obs = (compliance_min - 30)/5,
    rr_diff_max_scale = rr_diff_max/5,
    tv_cc_kg_scale = tv_cc_kg - 6,
    min_ph_scale = (min_ph - 7.4)/.1,
    mv_obs_max_scale = (mv_obs_max -10),
    plat_max_scale = (plat_estimate_max-20)/5, 
    plat_max_scale_obs = (plat_max-20)/5, 
    sofa_score_scale=(sofa_score-8))

#Set reference levels for factors for regressions 1) Convert to an unordered factor, 2) Relevel to set the reference group
rose_analytic_df$sars_cov2_positive <- factor(rose_analytic_df$sars_cov2_positive, ordered = FALSE)
rose_analytic_df$sars_cov2_positive <- relevel(rose_analytic_df$sars_cov2_positive, ref = "Positive")

rose_analytic_df$race_ethnicity <- factor(rose_analytic_df$race_ethnicity, ordered = FALSE)
rose_analytic_df$race_ethnicity <- relevel(rose_analytic_df$race_ethnicity, ref = "White, non-Hispanic")

rose_analytic_df$first_rose_mode <- factor(rose_analytic_df$first_rose_mode, ordered = FALSE)

rose_analytic_df$enrollment_location_type <- factor(rose_analytic_df$enrollment_location_type, ordered = FALSE)
rose_analytic_df$enrollment_location_type <- relevel(rose_analytic_df$enrollment_location_type, ref = "medical_icu")

rose_analytic_df$nee_pressor_dose <- factor(rose_analytic_df$nee_pressor_dose, ordered = FALSE)
rose_analytic_df$nee_pressor_dose <- relevel(rose_analytic_df$nee_pressor_dose, ref = "1")

rose_analytic_df$or_before_enrollment <- factor(rose_analytic_df$or_before_enrollment)
rose_analytic_df$ph_715 <- factor(rose_analytic_df$ph_715)

rose_analytic_df$study_period <- factor(rose_analytic_df$study_period)
rose_analytic_df$study_period <- relevel(rose_analytic_df$study_period, ref = "Pre-ROSE/Pre-COVID")

```



```{r}
#plots -
unproned_cohort<- rose_analytic_df %>% filter(prone_48==0)
proned_cohort<- rose_analytic_df %>% filter(prone_48==1)

#Univariate graphs - unproned cohort (prone_48==0)
#group by rounded pf and count up how many on paralytics
pf_plot<- unproned_cohort %>% group_by(pfround) %>% summarise(total = n(), yes_count=sum(any_paralytic_48), no_count=total-yes_count, percent_yes=100 * yes_count/total)
ggplot(pf_plot, aes(x= pfround, y = percent_yes)) + geom_point() + theme_classic()
write.csv(pf_plot, paste0(project_location, '/project_output_UPLOAD/', site, '_pf_plot_unproned.csv'))

#group by MV_obs and count up how many on paralytics
mv_plot<- unproned_cohort %>% group_by(mv_obsround) %>% summarise(total = n(), yes_count=sum(any_paralytic_48), no_count=total-yes_count, percent_yes=100 * yes_count/total)
ggplot(mv_plot, aes(x= mv_obsround, y = percent_yes)) + geom_point() + theme_classic()
write.csv(mv_plot, paste0(project_location, '/project_output_UPLOAD/', site, '_mv_plot_unproned.csv'))

#group by RR_diff and count up how many on paralytics
rr_diff_plot<- unproned_cohort %>% group_by(rr_diff_max) %>% summarise(total = n(), yes_count=sum(any_paralytic_48), no_count=total-yes_count, percent_yes=100 * yes_count/total)
ggplot(rr_diff_plot, aes(x= rr_diff_max, y = percent_yes)) + geom_point() + theme_classic()
write.csv(rr_diff_plot, paste0(project_location, '/project_output_UPLOAD/', site, '_rr_diff_plot_unproned.csv'))

#group by min_pH and count up how many on paralytics
min_ph_plot<- unproned_cohort %>% group_by(min_ph) %>% summarise(total = n(), yes_count=sum(any_paralytic_48), no_count=total-yes_count, percent_yes=100 * yes_count/total)
ggplot(min_ph_plot, aes(x= min_ph, y = percent_yes)) + geom_point() + theme_classic()
write.csv(min_ph_plot, paste0(project_location, '/project_output_UPLOAD/', site, '_min_ph_plot_unproned.csv'))

#group by max_rass and count up how many on paralytics
max_rass_plot<- unproned_cohort %>% group_by(max_rass12) %>% summarise(total = n(), yes_count=sum(any_paralytic_48), no_count=total-yes_count, percent_yes=100 * yes_count/total)
ggplot(max_rass_plot, aes(x= max_rass12, y = percent_yes)) + geom_point() + theme_classic()
write.csv(max_rass_plot, paste0(project_location, '/project_output_UPLOAD/', site, '_max_rass_plot_unproned.csv'))

#group by min_rass and count up how many on paralytics
min_rass_plot<- unproned_cohort %>% group_by(min_rass12) %>% summarise(total = n(), yes_count=sum(any_paralytic_48), no_count=total-yes_count, percent_yes=100 * yes_count/total)
ggplot(min_rass_plot, aes(x= min_rass12, y = percent_yes)) + geom_point() + theme_classic()
write.csv(min_rass_plot, paste0(project_location, '/project_output_UPLOAD/', site, '_min_rass_plot_unproned.csv'))
```


```{r}
#Univariate models for primary outcome. 
# proning 
if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + prone_48 
main_mod <- glm(model_form_step, data = rose_analytic_df %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ prone_48 
main_mod <- glm(model_form_step, data = rose_analytic_df, family=binomial, na.action = na.omit)
}

summary(main_mod)
prone_summary <- model_summary_table(main_mod)

# study period
if(n_periods==3){
  if (n_hospitals>1) {
  model_form_step <- any_paralytic_48 ~ factor(hospital_id) + (study_period)
  main_mod <- glm(model_form_step, data = rose_analytic_df %>% filter(!is.na(hospital_id)), family=binomial)
  } else {
  model_form_step <- any_paralytic_48 ~ factor(study_period)
  main_mod <- glm(model_form_step, data = rose_analytic_df, family=binomial, na.action = na.omit)
  }
  summary(main_mod)
  period_summary <- model_summary_table(main_mod)


# proning and study period - interaction
  if (n_hospitals>1) {
  model_form_step <- any_paralytic_48 ~ factor(hospital_id) + study_period + prone_48 + study_period*prone_48
  main_mod <- glm(model_form_step, data = rose_analytic_df %>% filter(!is.na(hospital_id)), family=binomial)
  } else {
  model_form_step <- any_paralytic_48 ~ study_period + prone_48 + study_period*prone_48
  main_mod <- glm(model_form_step, data = rose_analytic_df, family=binomial, na.action = na.omit)
  }

  summary(main_mod)
  prone_period_summary_int <- model_summary_table(main_mod)

# proning and study period
  if (n_hospitals>1) {
  model_form_step <- any_paralytic_48 ~ factor(hospital_id) + study_period + prone_48 
  main_mod <- glm(model_form_step, data = rose_analytic_df %>% filter(!is.na(hospital_id)), family=binomial)
  } else {
  model_form_step <- any_paralytic_48 ~ study_period + prone_48 
  main_mod <- glm(model_form_step, data = rose_analytic_df, family=binomial, na.action = na.omit)
  }

  summary(main_mod)
  prone_period_summary <- model_summary_table(main_mod)
}

# hypoxemia
if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + first_rose_pf_all_scale 
main_mod <- glm(model_form_step, data = rose_analytic_df %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ first_rose_pf_all_scale 
main_mod <- glm(model_form_step, data = rose_analytic_df, family=binomial, na.action = na.omit)
}

summary(main_mod)
hypoxemia_summary <- model_summary_table(main_mod)

if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + first_rose_pf_all_scale 
main_mod <- glm(model_form_step, data = unproned_cohort %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ first_rose_pf_all_scale 
main_mod <- glm(model_form_step, data = unproned_cohort, family=binomial, na.action = na.omit)
}

summary(main_mod)
hypoxemia_summary_unproned <- model_summary_table(main_mod)

if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + first_rose_pf_all_scale 
main_mod <- glm(model_form_step, data = proned_cohort %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ first_rose_pf_all_scale 
main_mod <- glm(model_form_step, data = proned_cohort, family=binomial, na.action = na.omit)
}

summary(main_mod)
hypoxemia_summary_proned <- model_summary_table(main_mod)

# pH
if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + min_ph_scale 
main_mod <- glm(model_form_step, data = rose_analytic_df %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ min_ph_scale 
main_mod <- glm(model_form_step, data = rose_analytic_df, family=binomial, na.action = na.omit)
}

summary(main_mod)
ph_summary <- model_summary_table(main_mod)

if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + min_ph_scale 
main_mod <- glm(model_form_step, data = unproned_cohort %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ min_ph_scale 
main_mod <- glm(model_form_step, data = unproned_cohort, family=binomial, na.action = na.omit)
}

summary(main_mod)
ph_summary_unproned <- model_summary_table(main_mod)

if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + min_ph_scale 
main_mod <- glm(model_form_step, data = proned_cohort %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ min_ph_scale 
main_mod <- glm(model_form_step, data = proned_cohort, family=binomial, na.action = na.omit)
}

summary(main_mod)
ph_summary_proned <- model_summary_table(main_mod)

# mv_obs
if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + mv_obs_max_scale 
main_mod <- glm(model_form_step, data = rose_analytic_df %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ mv_obs_max_scale 
main_mod <- glm(model_form_step, data = rose_analytic_df, family=binomial, na.action = na.omit)
}

summary(main_mod)
mv_obs_summary <- model_summary_table(main_mod)

if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + min_ph_scale 
main_mod <- glm(model_form_step, data = unproned_cohort %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ min_ph_scale 
main_mod <- glm(model_form_step, data = unproned_cohort, family=binomial, na.action = na.omit)
}

summary(main_mod)
mv_obs_summary_unproned <- model_summary_table(main_mod)

if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + min_ph_scale 
main_mod <- glm(model_form_step, data = proned_cohort %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ min_ph_scale 
main_mod <- glm(model_form_step, data = proned_cohort, family=binomial, na.action = na.omit)
}

summary(main_mod)
mv_obs_summary_proned <- model_summary_table(main_mod)

# rr_obs
if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + rr_diff_max_scale 
main_mod <- glm(model_form_step, data = rose_analytic_df %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ rr_diff_max_scale 
main_mod <- glm(model_form_step, data = rose_analytic_df, family=binomial, na.action = na.omit)
}

summary(main_mod)
rr_diff_summary <- model_summary_table(main_mod)

if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + rr_diff_max_scale 
main_mod <- glm(model_form_step, data = unproned_cohort %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ rr_diff_max_scale 
main_mod <- glm(model_form_step, data = unproned_cohort, family=binomial, na.action = na.omit)
}

summary(main_mod)
rr_diff_summary_unproned <- model_summary_table(main_mod)

if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + rr_diff_max_scale 
main_mod <- glm(model_form_step, data = proned_cohort %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ rr_diff_max_scale 
main_mod <- glm(model_form_step, data = proned_cohort, family=binomial, na.action = na.omit)
}

summary(main_mod)
rr_diff_summary_proned <- model_summary_table(main_mod)

# rass/agitation
if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + max_rass12 
main_mod <- glm(model_form_step, data = rose_analytic_df %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ max_rass12 
main_mod <- glm(model_form_step, data = rose_analytic_df, family=binomial, na.action = na.omit)
}

summary(main_mod)
rass_max_summary <- model_summary_table(main_mod)

if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + max_rass12 
main_mod <- glm(model_form_step, data = unproned_cohort %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ max_rass12 
main_mod <- glm(model_form_step, data = unproned_cohort, family=binomial, na.action = na.omit)
}

summary(main_mod)
rass_max_summary_unproned <- model_summary_table(main_mod)

if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + max_rass12 
main_mod <- glm(model_form_step, data = proned_cohort %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ max_rass12 
main_mod <- glm(model_form_step, data = proned_cohort, family=binomial, na.action = na.omit)
}

summary(main_mod)
rass_max_summary_proned <- model_summary_table(main_mod)

# rass/deep sedation
if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + min_rass12 
main_mod <- glm(model_form_step, data = rose_analytic_df %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ min_rass12 
main_mod <- glm(model_form_step, data = rose_analytic_df, family=binomial, na.action = na.omit)
}

summary(main_mod)
rass_min_summary <- model_summary_table(main_mod)

if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + min_rass12 
main_mod <- glm(model_form_step, data = unproned_cohort %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ min_rass12 
main_mod <- glm(model_form_step, data = unproned_cohort, family=binomial, na.action = na.omit)
}

summary(main_mod)
rass_min_summary_unproned <- model_summary_table(main_mod)

if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + min_rass12 
main_mod <- glm(model_form_step, data = proned_cohort %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ min_rass12 
main_mod <- glm(model_form_step, data = proned_cohort, family=binomial, na.action = na.omit)
}

summary(main_mod)
rass_min_summary_proned <- model_summary_table(main_mod)

#Summary Table With All Models
if(n_periods==3){
  main_table <- bind_rows(
    data.frame(site = c("Prone")),
    prone_summary,
    data.frame(site = c("Study period")),
    period_summary,
    data.frame(site = c("Prone*Study period")),
    prone_period_summary_int,
    data.frame(site = c("Prone, Study period")),
    prone_period_summary,
    data.frame(site = c("Hypoxemia")),
    hypoxemia_summary,
    data.frame(site = c("Hypoxemia_unproned")),
    hypoxemia_summary_unproned,
    data.frame(site = c("Hypoxemia_proned")),
    hypoxemia_summary_proned,
    data.frame(site = c("pH")),
    ph_summary,
    data.frame(site = c("pH_unproned")),
    ph_summary_unproned,
    data.frame(site = c("pH_proned")),
    ph_summary_proned,
    data.frame(site = c("MV")),
    mv_obs_summary,
    data.frame(site = c("MV_unproned")),
    mv_obs_summary_unproned,
    data.frame(site = c("MV_proned")),
    mv_obs_summary_proned,
    data.frame(site = c("RR")),
    rr_diff_summary,
    data.frame(site = c("RR_unproned")),
    rr_diff_summary_unproned,
    data.frame(site = c("RR_proned")),
    rr_diff_summary_proned,
    data.frame(site = c("Rass agitation/Max")),
    rass_max_summary,
    data.frame(site = c("Rass agitation/Max")),
    rass_max_summary_unproned,
    data.frame(site = c("Rass agitation/Max")),
    rass_max_summary_proned,
    data.frame(site = c("Rass deep sedation/Min")),
    rass_min_summary,
    data.frame(site = c("Rass deep sedation/Min")),
    rass_min_summary_unproned,
    data.frame(site = c("Rass deep sedation/Min")),
    rass_min_summary_proned)
} else{
  main_table <- bind_rows(
     data.frame(site = c("Prone")),
    prone_summary,
    data.frame(site = c("Study period")),
    period_summary,
    data.frame(site = c("Prone*Study period")),
    prone_period_summary_int,
    data.frame(site = c("Prone, Study period")),
    prone_period_summary,
    data.frame(site = c("Hypoxemia")),
    hypoxemia_summary,
    data.frame(site = c("Hypoxemia_unproned")),
    hypoxemia_summary_unproned,
    data.frame(site = c("Hypoxemia_proned")),
    hypoxemia_summary_proned,
    data.frame(site = c("pH")),
    ph_summary,
    data.frame(site = c("pH_unproned")),
    ph_summary_unproned,
    data.frame(site = c("pH_proned")),
    ph_summary_proned,
    data.frame(site = c("MV")),
    mv_obs_summary,
    data.frame(site = c("MV_unproned")),
    mv_obs_summary_unproned,
    data.frame(site = c("MV_proned")),
    mv_obs_summary_proned,
    data.frame(site = c("RR")),
    rr_diff_summary,
    data.frame(site = c("RR_unproned")),
    rr_diff_summary_unproned,
    data.frame(site = c("RR_proned")),
    rr_diff_summary_proned,
    data.frame(site = c("Rass agitation/Max")),
    rass_max_summary,
    data.frame(site = c("Rass agitation/Max")),
    rass_max_summary_unproned,
    data.frame(site = c("Rass agitation/Max")),
    rass_max_summary_proned,
    data.frame(site = c("Rass deep sedation/Min")),
    rass_min_summary,
    data.frame(site = c("Rass deep sedation/Min")),
    rass_min_summary_unproned,
    data.frame(site = c("Rass deep sedation/Min")),
    rass_min_summary_proned)
}
# Write the table to a CSV file
write.csv(main_table, paste0(project_location, '/project_output_UPLOAD/', site, '_univariate_models.csv'))

```

```{r Each Hospital or ICU Individually}
#function will skip and continue processing if convergence issues
safe_glm <- safely(function(df, predictor_var) {
  model_form <- reformulate(termlabels = predictor_var, response = "any_paralytic_48")
  glm(model_form, data = df, family = binomial, na.action = na.omit)
})

safe_tidy <- possibly(
  ~ tidy(.x, exponentiate = TRUE, conf.int = TRUE),
  otherwise = NULL
)

#proning
models_by_hospital_prone <- rose_analytic_df |>
  group_by(hospital_id) |>
  filter(!is.na(hospital_id)) |>
  nest() |>
  mutate(fit = map(data, ~ safe_glm(.x, "prone_48")),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})
    ) |>
  select(hospital_id, n, results) |>
  unnest(results)


models_by_icu_prone <- rose_analytic_df %>%
  group_by(enrollment_location_type) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, "prone_48")),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})
    ) %>%
  select(enrollment_location_type,n,  results) %>%
  unnest(results)

models_by_hospital_icu_prone <- rose_analytic_df %>%
  group_by(hospital_id, enrollment_location_type) %>%
    filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, "prone_48")),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})
    ) %>%
  select(hospital_id,enrollment_location_type,n,  results) %>%
  unnest(results)

#study period
models_by_hospital_period <- rose_analytic_df %>%
  group_by(hospital_id) %>%
    filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, "study_period")),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
  results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)

models_by_icu_period <- rose_analytic_df %>%
  group_by(enrollment_location_type) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, "study_period")),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(enrollment_location_type,n,  results) %>%
  unnest(results)

models_by_hospital_icu_period <- rose_analytic_df %>%
  group_by(hospital_id, enrollment_location_type) %>%
    filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, "study_period")),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id,enrollment_location_type, n, results) %>%
  unnest(results)

#proning and study period
models_by_hospital_period_prone <- rose_analytic_df %>%
  group_by(hospital_id) %>%
    filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("study_period", "prone_48"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id,n,  results) %>%
  unnest(results)

models_by_icu_period_prone <- rose_analytic_df %>%
  group_by(enrollment_location_type) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("study_period", "prone_48"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(enrollment_location_type,n,  results) %>%
  unnest(results)

models_by_hospital_icu_period_prone <- rose_analytic_df %>%
  group_by(hospital_id, enrollment_location_type) %>%
    filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("study_period", "prone_48"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
  results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id,enrollment_location_type,n,  results) %>%
  unnest(results)

#hypoxia
models_by_hospital_hypoxia <- rose_analytic_df %>%
  group_by(hospital_id) %>%
    filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("first_rose_pf_all_scale"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
  results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)

models_by_icu_hypoxia <- rose_analytic_df %>%
  group_by(enrollment_location_type) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("first_rose_pf_all_scale"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(enrollment_location_type, n, results) %>%
  unnest(results)

models_by_hospital_icu_hypoxia <- rose_analytic_df %>%
  group_by(hospital_id, enrollment_location_type) %>%
    filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("first_rose_pf_all_scale"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id,enrollment_location_type,n,  results) %>%
  unnest(results)

#hypoxia
models_by_hospital_hypoxia_unproned <- unproned_cohort %>%
  group_by(hospital_id) %>%
    filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("first_rose_pf_all_scale"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
   results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)

models_by_icu_hypoxia_unproned <- unproned_cohort %>%
  group_by(enrollment_location_type) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("first_rose_pf_all_scale"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(enrollment_location_type,n,  results) %>%
  unnest(results)

models_by_hospital_icu_hypoxia_unproned <- unproned_cohort %>%
  group_by(hospital_id, enrollment_location_type) %>%
    filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("first_rose_pf_all_scale"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id,enrollment_location_type,n,  results) %>%
  unnest(results)

#hypoxia
models_by_hospital_hypoxia_proned <- proned_cohort %>%
  group_by(hospital_id) %>%
    filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("first_rose_pf_all_scale"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)

models_by_icu_hypoxia_proned <- proned_cohort %>%
  group_by(enrollment_location_type) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("first_rose_pf_all_scale"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
     n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(enrollment_location_type, n, results) %>%
  unnest(results)

models_by_hospital_icu_hypoxia_proned <- proned_cohort %>%
  group_by(hospital_id, enrollment_location_type) %>%
    filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(
    fit = map(data, ~ safe_glm(.x, c("first_rose_pf_all_scale"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
    n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})
  ) %>%
  select(hospital_id, enrollment_location_type, n, results) %>%
  unnest(results)

# pH
models_by_hospital_ph <- rose_analytic_df %>%
  group_by(hospital_id) %>%
    filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("min_ph_scale"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)

models_by_hospital_ph_unproned <- unproned_cohort %>%
  group_by(hospital_id) %>%
    filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("min_ph_scale"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)

models_by_hospital_rr_unproned <- unproned_cohort %>%
  group_by(hospital_id) %>%
    filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("rr_diff_max_scale"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)

models_by_hospital_mv_unproned <- unproned_cohort %>%
  group_by(hospital_id) %>%
    filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("mv_obs_max_scale"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)


#Summary Table With All Models
if(n_periods==3){
  main_table <- bind_rows(
    data.frame(site = c("Prone - hospital")),
    models_by_hospital_prone,
    data.frame(site = c("Prone- icu")),
    models_by_icu_prone,
    data.frame(site = c("Prone - hospital/icu")),
    models_by_hospital_icu_prone,
    data.frame(site = c("Period - hospital")),
    models_by_hospital_period,
    data.frame(site = c("period- icu")),
    models_by_icu_period,
    data.frame(site = c("period - hospital/icu")),
    models_by_hospital_icu_period,
    data.frame(site = c("Prone/period - hospital")),
    models_by_hospital_period_prone,
    data.frame(site = c("Prone/period- icu")),
    models_by_icu_period_prone,
    data.frame(site = c("Prone/period - hospital/icu")),
    models_by_hospital_icu_period_prone,
    data.frame(site = c("hypoxia - hospital")),
    models_by_hospital_hypoxia,
    data.frame(site = c("hypoxia- icu")),
    models_by_icu_hypoxia,
    data.frame(site = c("hypoxia - hospital/icu")),
    models_by_hospital_icu_hypoxia,
    data.frame(site = c("hypoxia - hospital - unproned")),
    models_by_hospital_hypoxia_unproned,
    data.frame(site = c("hypoxia- icu - unproned")),
    models_by_icu_hypoxia_unproned,
    data.frame(site = c("hypoxia - hospital/icu - unproned")),
    models_by_hospital_icu_hypoxia_unproned,
    data.frame(site = c("hypoxia - hospital - proned")),
    models_by_hospital_hypoxia_proned,
    data.frame(site = c("hypoxia- icu - proned")),
    models_by_icu_hypoxia_proned,
    data.frame(site = c("hypoxia - hospital/icu - proned")),
    models_by_hospital_icu_hypoxia_proned, 
    data.frame(site = c("ph - hospital")),
    models_by_hospital_ph,
    data.frame(site = c("ph - hospital unproned")),
    models_by_hospital_ph_unproned,
    data.frame(site = c("rr - hospital unproned")),
    models_by_hospital_rr_unproned,
    data.frame(site = c("mv - hospital unproned")),
    models_by_hospital_mv_unproned
    )
} else{
  main_table <- bind_rows(
    data.frame(site = c("Prone - hospital")),
    models_by_hospital_prone,
    data.frame(site = c("Prone- icu")),
    models_by_icu_prone,
    data.frame(site = c("Prone - hospital/icu")),
    models_by_hospital_icu_prone,
    data.frame(site = c("hypoxia - hospital")),
    models_by_hospital_hypoxia,
    data.frame(site = c("hypoxia- icu")),
    models_by_icu_hypoxia,
    data.frame(site = c("hypoxia - hospital/icu")),
    models_by_hospital_icu_hypoxia,
    data.frame(site = c("hypoxia - hospital - unproned")),
    models_by_hospital_hypoxia_unproned,
    data.frame(site = c("hypoxia- icu - unproned")),
    models_by_icu_hypoxia_unproned,
    data.frame(site = c("hypoxia - hospital/icu - unproned")),
    models_by_hospital_icu_hypoxia_unproned,
    data.frame(site = c("hypoxia - hospital - proned")),
    models_by_hospital_hypoxia_proned,
    data.frame(site = c("hypoxia- icu - proned")),
    models_by_icu_hypoxia_proned,
    data.frame(site = c("hypoxia - hospital/icu - proned")),
    models_by_hospital_icu_hypoxia_proned,
    data.frame(site = c("ph - hospital")),
    models_by_hospital_ph,
    data.frame(site = c("ph - hospital unproned")),
    models_by_hospital_ph_unproned,
    data.frame(site = c("rr - hospital unproned")),
    models_by_hospital_rr_unproned,
    data.frame(site = c("mv - hospital unproned")),
    models_by_hospital_mv_unproned
    )
}

main_table<- main_table |>
  mutate(
    estimate= case_when(n>=10~estimate),
    std.error= case_when(n>=10~std.error),
    statistic= case_when(n>=10~statistic),
    p.value= case_when(n>=10~p.value),
    conf.low= case_when(n>=10~conf.low),
    conf.high= case_when(n>=10~conf.high))
         
# Write the table to a CSV file
write.csv(main_table, paste0(project_location, '/project_output_UPLOAD/', site, '_univariate_models_hospital.csv'))

```

```{r}
#Univariate models for primary outcome, among patients who ARE NOT PRONED in 48h (SA)
# study period
if(n_periods==3){
  if (n_hospitals>1) {
  model_form_step <- any_paralytic_48 ~ factor(hospital_id) + (study_period)
  main_mod <- glm(model_form_step, data = unproned_cohort  %>% filter(!is.na(hospital_id)), family=binomial)
  } else {
  model_form_step <- any_paralytic_48 ~ factor(study_period)
  main_mod <- glm(model_form_step, data = unproned_cohort, family=binomial, na.action = na.omit)
  }

  summary(main_mod)
  period_summary_unproned <- model_summary_table(main_mod)
}

# hypoxemia
if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + first_rose_pf_all_scale 
main_mod <- glm(model_form_step, data = unproned_cohort %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ first_rose_pf_all_scale 
main_mod <- glm(model_form_step, data = unproned_cohort, family=binomial, na.action = na.omit)
}

summary(main_mod)
hypoxemia_summary_unproned <- model_summary_table(main_mod)

# mv_obs
if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + mv_obs_max_scale 
main_mod <- glm(model_form_step, data = unproned_cohort %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ mv_obs_max_scale 
main_mod <- glm(model_form_step, data = unproned_cohort, family=binomial, na.action = na.omit)
}

summary(main_mod)
mv_obs_summary_unproned <- model_summary_table(main_mod)

# rr_obs
if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + rr_diff_max_scale 
main_mod <- glm(model_form_step, data = unproned_cohort %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ rr_diff_max_scale 
main_mod <- glm(model_form_step, data = unproned_cohort, family=binomial, na.action = na.omit)
}

summary(main_mod)
rr_diff_summary_unproned <- model_summary_table(main_mod)


# rass/agitation
if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + max_rass12 
main_mod <- glm(model_form_step, data = unproned_cohort %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ max_rass12 
main_mod <- glm(model_form_step, data = unproned_cohort, family=binomial, na.action = na.omit)
}

summary(main_mod)
rass_max_summary_unproned <- model_summary_table(main_mod)


# rass/deep sedation
if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + min_rass 
main_mod <- glm(model_form_step, data = unproned_cohort %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ min_rass 
main_mod <- glm(model_form_step, data = unproned_cohort, family=binomial, na.action = na.omit)
}

summary(main_mod)
rass_min_summary_unproned <- model_summary_table(main_mod)

if(n_periods==3){
  main_table <- bind_rows(
    data.frame(site = c("Study period")),
    period_summary,
    data.frame(site = c("Hypoxemia")),
    hypoxemia_summary,
    data.frame(site = c("MV")),
    mv_obs_summary,
    data.frame(site = c("RR")),
    rr_diff_summary,
    data.frame(site = c("Rass agitation/Max")),
    rass_max_summary,
    data.frame(site = c("Rass deep sedation/Min")),
    rass_min_summary)
}else{
  main_table <- bind_rows(
    data.frame(site = c("Hypoxemia")),
    hypoxemia_summary,
    data.frame(site = c("MV")),
    mv_obs_summary,
    data.frame(site = c("RR")),
    rr_diff_summary,
    data.frame(site = c("Rass agitation/Max")),
    rass_max_summary,
    data.frame(site = c("Rass deep sedation/Min")),
    rass_min_summary)
}

# Write the table to a CSV file
write.csv(main_table, paste0(project_location, '/project_output_UPLOAD/', site, '_univariate_models_unproned_48.csv'))
```


```{r}
#Univariate comparisons between paralytic and non-paralytic groups for key predictors
prone_table <- as.data.frame.matrix(table(rose_analytic_df$prone_48, rose_analytic_df$any_paralytic_48))
hypoxemia_table<- as.data.frame.matrix(table(rose_analytic_df$hypoxemia, rose_analytic_df$any_paralytic_48))
if(n_periods==3){
  study_period_table <- as.data.frame.matrix(table(rose_analytic_df$study_period, rose_analytic_df$any_paralytic_48))
  study_period_table_unproned_cohort <- as.data.frame.matrix(table(unproned_cohort$study_period, unproned_cohort$any_paralytic_48))
}

hypoxemia_table_unproned_cohort<- as.data.frame.matrix(table(unproned_cohort$hypoxemia, unproned_cohort$any_paralytic_48))

if(n_periods==3){
  main_table <- bind_rows(
  data.frame(site = c("Prone")),
  prone_table,
  data.frame(site = c("Hypoxemia")),
  hypoxemia_table,
   data.frame(site = c("study period")),
  study_period_table,
  data.frame(site = c("Hypoxemia_unproned_cohort")),
  hypoxemia_table_unproned_cohort,
  data.frame(site = c("study period_unproned_cohort")),
  study_period_table_unproned_cohort
  )
}else{
  main_table <- bind_rows(
  data.frame(site = c("Prone")),
  prone_table,
  data.frame(site = c("Hypoxemia")),
  hypoxemia_table,
  data.frame(site = c("Hypoxemia_unproned_cohort")),
  hypoxemia_table_unproned_cohort
  )
}

main_table <- main_table %>% rename("no_paralytics"= "0", "paralytics" = "1")
main_table$paralytic_percent <- main_table$paralytics / (main_table$no_paralytics+ main_table$paralytics)


# Write the table to a CSV file
write.csv(main_table, paste0(project_location, '/project_output_UPLOAD/', site, '_univariate_intersectionality.csv'))

```


```{r - sensitivity analyses}

#No-OR
models_by_hospital_prone_no_or <- rose_analytic_df %>%
  filter(or_before_enrollment==0) %>%
  group_by(hospital_id) %>%
  filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, "prone_48")),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)

#hypoxia
models_by_hospital_hypoxia_no_or <- rose_analytic_df %>%
    filter(or_before_enrollment==0) %>%
  group_by(hospital_id) %>%
  filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("first_rose_pf_all_scale"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)

#No-COVID+
models_by_hospital_prone_no_covid <- rose_analytic_df %>%
  filter(covid_positive!=1) %>%
  group_by(hospital_id) %>%
  filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, "prone_48")),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)

#hypoxia
models_by_hospital_hypoxia_no_covid <- rose_analytic_df %>%
  filter(covid_positive!=1) %>%
  group_by(hospital_id) %>%
  filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("first_rose_pf_all_scale"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)

#Only current
models_by_hospital_prone_now <- rose_analytic_df %>%
  filter(study_period=="Post-ROSE/Post-COVID") %>%
  group_by(hospital_id) %>%
  filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, "prone_48")),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)

#hypoxia
models_by_hospital_hypoxia_now <- rose_analytic_df %>%
  filter(study_period=="Post-ROSE/Post-COVID") %>%
  group_by(hospital_id) %>%
  filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("first_rose_pf_all_scale"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)

#ards - icd
models_by_hospital_prone_ards <- rose_analytic_df %>%
  filter(ards_icd_10==1) %>%
  group_by(hospital_id) %>%
  filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, "prone_48")),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)

#hypoxia
models_by_hospital_hypoxia_ards <- rose_analytic_df %>%
  filter(ards_icd_10==1) %>%
  group_by(hospital_id) %>%
  filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("first_rose_pf_all_scale"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)

#severe hypoxemia
models_by_hospital_prone_severe <- rose_analytic_df %>%
  filter(severe_ards==1) %>%
  group_by(hospital_id) %>%
  filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, "prone_48")),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)

#hypoxia
models_by_hospital_hypoxia_severe <- rose_analytic_df %>%
  filter(severe_ards==1) %>%
  group_by(hospital_id) %>%
  filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("first_rose_pf_all_scale"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)

#hypoxia
models_by_hospital_hypoxia_unproned <- unproned_cohort %>%
  group_by(hospital_id) %>%
  filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("first_rose_pf_all_scale"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)

if(n_periods==3){
  #study period
models_by_hospital_period_no_or <- rose_analytic_df %>%
  filter(or_before_enrollment==0) %>%
  group_by(hospital_id) %>%
  filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, "study_period")),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)

#proning and study period
models_by_hospital_period_prone_no_or <- rose_analytic_df %>%
    filter(or_before_enrollment==0) %>%
  group_by(hospital_id) %>%
  filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("study_period", "prone_48"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id,n,  results) %>%
  unnest(results)

#study period
models_by_hospital_period_no_covid <- rose_analytic_df %>%
  filter(covid_positive!=1) %>%
  group_by(hospital_id) %>%
  filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, "study_period")),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)

#proning and study period
models_by_hospital_period_prone_no_covid <- rose_analytic_df %>%
  filter(covid_positive!=1) %>%
  group_by(hospital_id) %>%
  filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("study_period", "prone_48"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id,n,  results) %>%
  unnest(results)

#study period
models_by_hospital_period_ards <- rose_analytic_df %>%
  filter(ards_icd_10==1) %>%
  group_by(hospital_id) %>%
  filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, "study_period")),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)

#proning and study period
models_by_hospital_period_prone_ards <- rose_analytic_df %>%
  filter(ards_icd_10==1) %>%
  group_by(hospital_id) %>%
  filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("study_period", "prone_48"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id,n,  results) %>%
  unnest(results)


#study period
models_by_hospital_period_severe <- rose_analytic_df %>%
  filter(severe_ards==1) %>%
  group_by(hospital_id) %>%
  filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, "study_period")),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)

#proning and study period
models_by_hospital_period_prone_severe <- rose_analytic_df %>%
  filter(severe_ards==1) %>%
  group_by(hospital_id) %>%
  filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("study_period", "prone_48"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id,n,  results) %>%
  unnest(results)

#unproned
#study period
models_by_hospital_period_unproned <- unproned_cohort %>%
  group_by(hospital_id) %>%
  filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, "study_period")),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
    results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)
}


#Summary Table With All Models
if(n_periods==3){
  main_table <- bind_rows(
    data.frame(site = c("Prone - no or")),
    models_by_hospital_prone_no_or,
     data.frame(site = c("Period - no or")),
    models_by_hospital_period_no_or,
     data.frame(site = c("Prone/period - no or")),
    models_by_hospital_period_prone_no_or,
     data.frame(site = c("hypoxia - no or")),
    models_by_hospital_hypoxia_no_or,
    data.frame(site = c("Prone - no covid")),
    models_by_hospital_prone_no_covid,
     data.frame(site = c("Period - no covid")),
    models_by_hospital_period_no_covid,
     data.frame(site = c("Prone/period - no covid")),
    models_by_hospital_period_prone_no_covid,
     data.frame(site = c("hypoxia - no covid")),
    models_by_hospital_hypoxia_no_covid,
    data.frame(site = c("Prone - now")),
    models_by_hospital_prone_now,
    data.frame(site = c("hypoxia - now")),
    models_by_hospital_hypoxia_now,
    data.frame(site = c("Prone - ards")),
    models_by_hospital_prone_ards,
    data.frame(site = c("Period - ards")),
    models_by_hospital_period_ards,
    data.frame(site = c("Prone/period - ards")),
    models_by_hospital_period_prone_ards,
     data.frame(site = c("hypoxia - ards")),
    models_by_hospital_hypoxia_ards,
    
    data.frame(site = c("Prone - severe")),
    models_by_hospital_prone_severe,
    data.frame(site = c("Period - severe")),
    models_by_hospital_period_severe,
    data.frame(site = c("Prone/period - severe")),
    models_by_hospital_period_prone_severe,
    data.frame(site = c("hypoxia - severe")),
    models_by_hospital_hypoxia_severe,
    data.frame(site = c("Period - unproned")),
    models_by_hospital_period_unproned,
    data.frame(site = c("hypoxia - unproned")),
    models_by_hospital_hypoxia_unproned)
} else{
  main_table <- bind_rows(
    data.frame(site = c("Prone - no or")),
    models_by_hospital_prone_no_or,
    data.frame(site = c("hypoxia - no or")),
    models_by_hospital_hypoxia_no_or,
    data.frame(site = c("Prone - no covid")),
    models_by_hospital_prone_no_covid,
     data.frame(site = c("hypoxia - no covid")),
    models_by_hospital_hypoxia_no_covid,
    data.frame(site = c("Prone - now")),
    models_by_hospital_prone_now,
    data.frame(site = c("hypoxia - now")),
    models_by_hospital_hypoxia_now,
    data.frame(site = c("Prone - ards")),
    models_by_hospital_prone_ards,
    data.frame(site = c("hypoxia - ards")),
    models_by_hospital_hypoxia_ards,
    data.frame(site = c("Prone - severe")),
    models_by_hospital_prone_severe,
    data.frame(site = c("hypoxia - severe")),
    models_by_hospital_hypoxia_severe,
    data.frame(site = c("hypoxia - unproned")),
    models_by_hospital_hypoxia_unproned)
}
# Write the table to a CSV file
write.csv(main_table, paste0(project_location, '/project_output_UPLOAD/', site, '_univariate_sensitivity_analysis.csv'))

```


```{r}
#Multivariate analysis: 

if(n_periods==3){
if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + study_period + bmi_scale + age_scale + sofa_score_scale + race_ethnicity + or_before_enrollment + first_rose_fio2_scale + first_rose_peep_scale + criteria + first_rose_pf_all_scale + nee_pressor_dose + ett_to_enrolled + female  + enrollment_location_type  + deep_rass_max + rr_diff_max_scale + covid_positive + tv_cc_kg_scale  + mv_obs_max_scale  + plat_max_scale + compliance_scale + prone_48
main_mod <- glm(model_form_step,
          data = rose_analytic_df %>% filter(!is.na(hospital_id)), 
          family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ study_period + bmi_scale + age_scale + sofa_score_scale + race_ethnicity + or_before_enrollment + first_rose_fio2_scale + first_rose_peep_scale + criteria + first_rose_pf_all_scale + nee_pressor_dose + ett_to_enrolled + female  + enrollment_location_type  + deep_rass_max + rr_diff_max_scale + covid_positive + tv_cc_kg_scale  + mv_obs_max_scale  + plat_max_scale + compliance_scale + prone_48
main_mod <- glm(model_form_step,
          data = rose_analytic_df, 
          family=binomial, na.action = na.omit)
}

summary(main_mod)
main_mod_proning_summary <- model_summary_table(main_mod)
} else{
  
# main model if only 1 study period
if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) +  bmi_scale + age_scale + sofa_score_scale + race_ethnicity + or_before_enrollment + first_rose_fio2_scale + first_rose_peep_scale + criteria + first_rose_pf_all_scale + nee_pressor_dose + ett_to_enrolled + female  + enrollment_location_type  + deep_rass_max + rr_diff_max_scale + covid_positive + tv_cc_kg_scale  + mv_obs_max_scale  + plat_max_scale + compliance_scale + prone_48
main_mod <- glm(model_form_step,
          data = rose_analytic_df %>% filter(!is.na(hospital_id)), 
          family=binomial)
} else {
model_form_step <- any_paralytic_48 ~  bmi_scale + age_scale + sofa_score_scale + race_ethnicity + or_before_enrollment + first_rose_fio2_scale + first_rose_peep_scale + criteria + first_rose_pf_all_scale + nee_pressor_dose + ett_to_enrolled + female  + enrollment_location_type  + deep_rass_max + rr_diff_max_scale + covid_positive + tv_cc_kg_scale  + mv_obs_max_scale  + plat_max_scale + compliance_scale + prone_48
main_mod <- glm(model_form_step,
          data = rose_analytic_df, 
          family=binomial, na.action = na.omit)
}

summary(main_mod)
main_mod_proning_summary <- model_summary_table(main_mod)
}

#SA4: Subset of patients IMV 2022-2024; Identifying predictors of paralytics within 48 hours, including estimated compliance and plateau pressure
if (n_hospitals>1) {
model_form_step <- any_paralytic_48 ~ factor(hospital_id) + bmi_scale + age_scale + sofa_score_scale + race_ethnicity + or_before_enrollment + first_rose_fio2_scale + first_rose_peep_scale +  criteria + first_rose_pf_all_scale + nee_pressor_dose + ett_to_enrolled + female  + enrollment_location_type  + deep_rass_max + rr_diff_max_scale + covid_positive + tv_cc_kg_scale  + mv_obs_max_scale  + plat_max_scale + compliance_scale+ prone_48
main_mod_current <- glm(model_form_step,
          data = rose_analytic_df %>% filter(!is.na(hospital_id) & t_rose_first>=as.POSIXct("2022-01-01", tz=site_time_zone)), 
          family=binomial)
} else {
model_form_step <- any_paralytic_48 ~ bmi_scale + age_scale + sofa_score_scale + race_ethnicity + or_before_enrollment + first_rose_fio2_scale + first_rose_peep_scale +  criteria + first_rose_pf_all_scale + nee_pressor_dose + ett_to_enrolled + female  + enrollment_location_type  + deep_rass_max + rr_diff_max_scale + covid_positive + tv_cc_kg_scale  + mv_obs_max_scale  + plat_max_scale + compliance_scale+ prone_48
main_mod_current <- glm(model_form_step,
          data = subset(rose_analytic_df, t_rose_first>=as.POSIXct("2022-01-01", tz=site_time_zone)), 
          family=binomial, na.action = na.omit)
}

summary(main_mod_current)
main_mod_summary_sa4 <- model_summary_table(main_mod_current)

  
#extended propensity score model  
if (n_hospitals>1) {
    model_form_step <- any_paralytic_48 ~ factor(hospital_id) +  or_before_enrollment + first_rose_fio2_scale + first_rose_peep_scale  + first_rose_pf_all_scale + deep_rass_max + rr_diff_max_scale   + mv_obs_max_scale  + plat_max_scale + compliance_scale + prone_48 + ph_715
    main_mod <- glm(model_form_step,
                    data = rose_analytic_df %>% filter(!is.na(hospital_id)), 
                    family=binomial)
  } else {
    model_form_step <- any_paralytic_48 ~  or_before_enrollment + first_rose_fio2_scale + first_rose_peep_scale  + first_rose_pf_all_scale +  deep_rass_max + rr_diff_max_scale   + mv_obs_max_scale  + plat_max_scale + compliance_scale + prone_48 + ph_715
    main_mod <- glm(model_form_step,
                    data = rose_analytic_df, 
                    family=binomial, na.action = na.omit)
  }
  
  summary(main_mod)
  propensity_summary <- model_summary_table(main_mod)


#Summary Table With All Models
main_table <- bind_rows(
  data.frame(site = c("Main model_proning")),
  main_mod_proning_summary,
  data.frame(site= c("Extended Propensity score")),
  propensity_summary,
   data.frame(site = c("SA4: Current practice 2022-2024")),
  main_mod_summary_sa4,
)
# Write the table to a CSV file
write.csv(main_table, paste0(project_location, '/project_output_UPLOAD/', site, '_adjusted_models.csv'))

```


```{r TTE, mortality outcome}

#Mortality - add landmark analysis to address immortal time bias
if (n_hospitals>1) {
model_form_step <- death_or_hospice ~ factor(hospital_id) + any_paralytic_48
  main_mod <- glm(model_form_step, data = rose_analytic_df %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- death_or_hospice ~ factor(any_paralytic_48)
main_mod <- glm(model_form_step, data = rose_analytic_df, family=binomial, na.action = na.omit)
}

summary(main_mod)
mortality_univariate <- model_summary_table(main_mod)

#multivariate
if (n_hospitals>1) {
model_form_step <- death_or_hospice ~ factor(hospital_id) + any_paralytic_48  + age_scale + sofa_score_scale + or_before_enrollment + first_rose_pf_all_scale + nee_pressor_dose + covid_positive +prone_48
  main_mod <- glm(model_form_step, data = rose_analytic_df %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- death_or_hospice ~ factor(any_paralytic_48) + age_scale + sofa_score_scale + or_before_enrollment + first_rose_pf_all_scale + nee_pressor_dose + covid_positive +prone_48
main_mod <- glm(model_form_step, data = rose_analytic_df, family=binomial, na.action = na.omit)
}

summary(main_mod)
mortality_multivariate <- model_summary_table(main_mod)

if (n_hospitals>1) {
model_form_step <- death_or_hospice ~ factor(hospital_id) + factor(any_paralytic_48) + bmi_scale + age_scale + sofa_score_scale  + or_before_enrollment + first_rose_pf_all_scale + nee_pressor_dose + female  + deep_rass_max + covid_positive + compliance_scale + prone_48
  main_mod <- glm(model_form_step, data = rose_analytic_df %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- death_or_hospice ~  factor(any_paralytic_48) + bmi_scale + age_scale + sofa_score_scale  + or_before_enrollment + first_rose_pf_all_scale + nee_pressor_dose + female  + deep_rass_max + covid_positive + compliance_scale + prone_48
main_mod <- glm(model_form_step, data = rose_analytic_df, family=binomial, na.action = na.omit)
}

summary(main_mod)
mortality_multivariate_2 <- model_summary_table(main_mod)

#landmark analysis - subset of patients alive/in cohort at 48h
rose_analytic_df<- rose_analytic_df %>% mutate(incohort_48h= fifelse(final_discharge_dttm> t_rose_first + dhours(48), 1, 0))
landmark <- rose_analytic_df %>% filter(incohort_48h==1)

if (n_hospitals>1) {
model_form_step <- death_or_hospice ~ factor(hospital_id) + any_paralytic_48
  main_mod <- glm(model_form_step, data = landmark %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- death_or_hospice ~ factor(any_paralytic_48)
main_mod <- glm(model_form_step, data = landmark, family=binomial, na.action = na.omit)
}

summary(main_mod)
mortality_univariate_la <- model_summary_table(main_mod)

#adjust 
if (n_hospitals>1) {
model_form_step <- death_or_hospice ~ factor(hospital_id) + any_paralytic_48  + age_scale + sofa_score_scale + or_before_enrollment + first_rose_pf_all_scale + nee_pressor_dose + covid_positive +prone_48
  main_mod <- glm(model_form_step, data = landmark %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- death_or_hospice ~ factor(any_paralytic_48) + age_scale + sofa_score_scale + or_before_enrollment + first_rose_pf_all_scale + nee_pressor_dose + covid_positive +prone_48
main_mod <- glm(model_form_step, data = landmark, family=binomial, na.action = na.omit)
}

summary(main_mod)
mortality_multivariate_la <- model_summary_table(main_mod)

#adjust 
if (n_hospitals>1) {
model_form_step <- death_or_hospice ~ factor(hospital_id) + any_paralytic_48  + age_scale + sofa_score_scale + or_before_enrollment + first_rose_pf_all_scale + nee_pressor_dose + covid_positive +prone_48 + ards_icd_10
  main_mod <- glm(model_form_step, data = landmark %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- death_or_hospice ~ factor(any_paralytic_48) + age_scale + sofa_score_scale + or_before_enrollment + first_rose_pf_all_scale + nee_pressor_dose + covid_positive +prone_48+ ards_icd_10
main_mod <- glm(model_form_step, data = landmark, family=binomial, na.action = na.omit)
}

summary(main_mod)
mortality_multivariate_la <- model_summary_table(main_mod)

if (n_hospitals>1) {
model_form_step <- death_or_hospice ~ factor(hospital_id) + factor(any_paralytic_48) + bmi_scale + age_scale + sofa_score_scale  + or_before_enrollment + first_rose_pf_all_scale + nee_pressor_dose + female  + deep_rass_max + covid_positive + compliance_scale + prone_48 +ards_icd_10
  main_mod <- glm(model_form_step, data = landmark %>% filter(!is.na(hospital_id)), family=binomial)
} else {
model_form_step <- death_or_hospice ~  factor(any_paralytic_48) + bmi_scale + age_scale + sofa_score_scale  + or_before_enrollment + first_rose_pf_all_scale + nee_pressor_dose + female  + (deep_rass_max) + covid_positive + compliance_scale + prone_48+ards_icd_10
main_mod <- glm(model_form_step, data = landmark, family=binomial, na.action = na.omit)
}

summary(main_mod)
mortality_multivariate_la_2 <- model_summary_table(main_mod)

safe_glm <- safely(function(df, predictor_var) {
  model_form <- reformulate(termlabels = predictor_var, response = "death_or_hospice")
  glm(model_form, data = df, family = binomial, na.action = na.omit)
})

mortality_by_hospital_a <- landmark %>%
  group_by(hospital_id) %>%
    filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("any_paralytic_48", "bmi_scale", "age_scale", "sofa_score_scale", "or_before_enrollment", "first_rose_pf_all_scale", "nee_pressor_dose", "female", "deep_rass_max", "covid_positive", "compliance_scale", "prone_48", "ards_icd_10"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)


mortality_by_hospital_a_some <- landmark %>%
  group_by(hospital_id) %>%
    filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, c("any_paralytic_48",  "age_scale", "sofa_score_scale", "or_before_enrollment", "first_rose_pf_all_scale", "nee_pressor_dose",  "covid_positive",  "prone_48", "ards_icd_10"))),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)

mortality_by_hospital <- landmark %>%
  group_by(hospital_id) %>%
    filter(!is.na(hospital_id)) %>%
  nest() %>%
  mutate(fit = map(data, ~ safe_glm(.x, "any_paralytic_48")),
    model = map(fit, "result"),
    error = map(fit, "error"),
        n = map_int(model, ~ if (is.null(.x)) NA_integer_ else nobs(.x)),
results = map(model, ~ {
  if (is.null(.x)) {
    tibble()
  } else {
    result <- safe_tidy(.x)
    if (is.null(result)) {
      tidy(.x, exponentiate = TRUE, conf.int = FALSE) %>%
        mutate(conf.low = NA_real_, conf.high = NA_real_)
    } else {
      result
    }
  }
})) %>%
  select(hospital_id, n, results) %>%
  unnest(results)

#Summary Table With All Models
main_table <- bind_rows(
  data.frame(site = c("Univariate, mortality")),
  mortality_univariate,
  data.frame(site = c("Multivariate, mortality")),
  mortality_multivariate,
  data.frame(site = c("Multivariate, mortality, 2")),
  mortality_multivariate_2,
  data.frame(site = c("Multivariate, landmark analysis")),
  mortality_multivariate_la,
  data.frame(site = c("Multivariate, landmark analysis")),
  mortality_multivariate_la,
  data.frame(site = c("Multivariate, landmark analysis 2")),
  mortality_multivariate_la_2, 
  data.frame(site = ("Hospital_landmark, unadjusted")),
  mortality_by_hospital,
  data.frame(site = ("Hospital_landmark, adjusted some")),
  mortality_by_hospital_a_some,
  data.frame(site = ("Hospital_landmark, adjusted full")),
  mortality_by_hospital_a,
  
)
# Write the table to a CSV file
write.csv(main_table, paste0(project_location, '/project_output_UPLOAD/', site, '_mortality_models.csv'))

```

```{r Descriptive data for paralytic use continuous/not among ALL patients who meet ROSE criteria}
#Look at use of continuous vs intermittent pushes, and how many intermittent pushes

#continuous
continuous<- rose_analytic_df |>
  filter(any_paralytic_48==1 & initial_paralytic_type=="continuous") |>
  mutate(ett_to_paralytic_c_all=as.numeric(ett_to_paralytic_c_all)/60/60/24, 
         any_proning=fifelse(!is.na(prone_episodes), 1, 0))
  
to_tab <- c(
  'continous_paralytic_given',
  'prone_48',
  'ratio_at_paralytics_c_all', 
   'hospital_id',
  'sars_cov2_positive',
  'enrollment_location_type')

#Factor Variables
factors_tab <- c(
  'continous_paralytic_given',
  'prone_48', 
  'hospital_id',
  'sars_cov2_positive',
  'enrollment_location_type'
)

if(n_hospitals >1){
  tab2_continuous <- CreateTableOne(vars = to_tab, data=continuous %>% filter(!is.na(hospital_id)), factorVars = factors_tab, strata="hospital_id")
}else {
  tab2_continuous <- CreateTableOne(vars = to_tab, data=continuous, factorVars = factors_tab)
}
tab2_excel <- as.data.frame(print(tab2_continuous, printToggle = FALSE, missing = TRUE)) |>
  rownames_to_column('characteristic') |>
  rename(percent_missing = Missing) |>
  mutate(site = site) |>
  relocate(site, .after = characteristic)
write.csv(tab2_excel, file=paste0(project_location, '/project_output_UPLOAD/', site, '_Table_paralytics_continuous_rose.csv'))
rm(tab2_excel)

#intermittent
intermittent<- rose_analytic_df |>
  filter(any_paralytic_48==1 &initial_paralytic_type=="intermittent") |>
    mutate(ett_to_paralytic_i_all=as.numeric(ett_to_paralytic_i_all)/60/60/24, 
         any_proning=fifelse(!is.na(prone_episodes), 1, 0))

to_tab <- c(
  'intermittent_paralytic_given',
  'prone_48', 
  'hospital_id',
  'sars_cov2_positive',
  'enrollment_location_type', 
  'then_paralytic_c')

#Factor Variables
factors_tab <- c(
  'intermittent_paralytic_given',
  'prone_48', 
  'hospital_id',
  'sars_cov2_positive',
  'enrollment_location_type',
  'then_paralytic_c'
)

if(n_hospitals >1){
  tab2_intermittent <- CreateTableOne(vars = to_tab, data=intermittent %>% filter(!is.na(hospital_id)), factorVars = factors_tab, strata="hospital_id")
}else {
  tab2_intermittent <- CreateTableOne(vars = to_tab, data=intermittent, factorVars = factors_tab)
}

tab2_excel <- as.data.frame(print(tab2_intermittent, printToggle = FALSE, missing = TRUE)) |>
  rownames_to_column('characteristic') |>
  rename(percent_missing = Missing) |>
  mutate(site = site) |>
  relocate(site, .after = characteristic) |>
  # Replace cells where the count (number before parenthesis) is < 10
  mutate(across(-c(characteristic, site, percent_missing), ~ {
    counts <- as.numeric(gsub("^\\s*([0-9]+)\\s*\\(.*", "\\1", .x))
    fifelse(!is.na(counts) & counts < 10 & counts > 0  & characteristic != "n" & characteristic !="then_paralytic_c = 1 (%)", "<10"
            , .x)
    }))
write.csv(tab2_excel, file=paste0(project_location, '/project_output_UPLOAD/', site, '_Table_paralytics_intermittent_rose.csv'))
rm(tab2_excel)

```


```{r Last Piece Create a Table with Observed and Expected Paralytic Counts/Rates by Hospital and proning status}
#This Aggregate Data Will be Used for Risk and Reliability Adjusted Paralytic Rate Estimates by Hospital
#Generate Paralytics Propensity Score (Don't Account for Hospital Here)
alt_form <- any_paralytic_48 ~  first_rose_pf_all_scale + ph_715 + prone_48 + study_period

alt_mod <- glm(alt_form,
               data = rose_analytic_df %>% filter(!is.na(hospital_id)), 
               family=binomial)

#Collect Coefficient and Covariance Matrix for Centralized Creation of Global Coefficient
propensity_build_estimates <- model_summary_table(alt_mod)
propensity_build_covariance <- as.data.frame(vcov(alt_mod))

write.csv(propensity_build_estimates, paste0(project_location, '/project_output_UPLOAD/', site, '_propensity_build_estimates.csv'))
write.csv(propensity_build_covariance, paste0(project_location, '/project_output_UPLOAD/', site, '_propensity_build_covariance.csv'))

#Extract Dataset from Model
df <- alt_mod$data

#Propensity Score Taken from Prediction
df$paralytics_propensity <- predict(alt_mod, newdata=df, type = 'response')

#Each Site Aggregates Data
#Create Aggregate Dataset with Observed and Expected Events as well as N
df_agg <- df |>
  group_by(hospital_id) |>
  filter(!is.na(hospital_id)) |>
  summarise(
    n_patients = n(),
    observed_paralytics = sum(any_paralytic_48, na.rm=TRUE),
    paralytics_rate_observed = mean(any_paralytic_48, na.rm=TRUE),
    paralytics_rate_adjust = mean(paralytics_propensity, na.rm = TRUE)
  ) |>
  ungroup() |>
  mutate(expected_paralytics=round((paralytics_rate_adjust*n_patients), digits = 0)) |>
  mutate(not_paralytics=n_patients-observed_paralytics)

#Save CSV
write.csv(df_agg, paste0(project_location, '/project_output_UPLOAD/', site, '_aggregate_expected_paralytics.csv'))

#This Aggregate Data Will be Used for Risk and Reliability Adjusted Paralytic Rate Estimates by Hospital, proning
#Generate Paralytics Propensity Score (Don't Account for Hospital or proning status Here)
alt_form <- any_paralytic_48 ~ first_rose_pf_all_scale + ph_715  + study_period

alt_mod <- glm(alt_form,
               data = rose_analytic_df %>% filter(!is.na(hospital_id)), 
               family=binomial)

#Collect Coefficient and Covariance Matrix for Centralized Creation of Global Coefficient
propensity_build_estimates <- model_summary_table(alt_mod)
propensity_build_covariance <- as.data.frame(vcov(alt_mod))

write.csv(propensity_build_estimates, paste0(project_location, '/project_output_UPLOAD/', site, '_propensity_build_estimates_no_proning.csv'))
write.csv(propensity_build_covariance, paste0(project_location, '/project_output_UPLOAD/', site, '_propensity_build_covariance_no_proning.csv'))

#Extract Dataset from Model
df <- alt_mod$data

#Propensity Score Taken from Prediction
df$paralytics_propensity <- predict(alt_mod, newdata=df %>% filter(!is.na(hospital_id)), type = 'response')

#Create Aggregate Dataset with Observed and Expected Events as well as N Broken Out by Proning Status
df_agg_para_prone_status <- df |>
  group_by(hospital_id, prone_48) |>
  summarise(
    n_patients = n(),
    observed_paralytics = sum(any_paralytic_48, na.rm=TRUE),
    paralytics_rate_observed = mean(any_paralytic_48, na.rm=TRUE),
    paralytics_rate_adjust = mean(paralytics_propensity, na.rm = TRUE)
  ) |>
  ungroup() |>
  filter(!is.na(hospital_id)) |>
  mutate(expected_paralytics=round((paralytics_rate_adjust*n_patients), digits = 0)) |>
  mutate(not_paralytics=n_patients-observed_paralytics)

#Save CSV
write.csv(df_agg_para_prone_status, paste0(project_location, '/project_output_UPLOAD/', site, '_aggregate_expected_paralytics_wprone_Status.csv'))

#This Aggregate Data Will be Used for Risk and Reliability Adjusted Paralytic Rate Estimates by Hospital, proning
#Generate Paralytics Propensity Score (Don't Account for Hospital, period, or proning status Here)
alt_form <- any_paralytic_48 ~ first_rose_pf_all_scale + ph_715  

alt_mod <- glm(alt_form,
               data = rose_analytic_df %>% filter(!is.na(hospital_id)), 
               family=binomial)

#Collect Coefficient and Covariance Matrix for Centralized Creation of Global Coefficient
propensity_build_estimates <- model_summary_table(alt_mod)
propensity_build_covariance <- as.data.frame(vcov(alt_mod))

write.csv(propensity_build_estimates, paste0(project_location, '/project_output_UPLOAD/', site, '_propensity_build_estimates_no_proning_nosp.csv'))
write.csv(propensity_build_covariance, paste0(project_location, '/project_output_UPLOAD/', site, '_propensity_build_covariance_no_proning_nosp.csv'))

#Extract Dataset from Model
df <- alt_mod$data

#Propensity Score Taken from Prediction
df$paralytics_propensity <- predict(alt_mod, newdata=df %>% filter(!is.na(hospital_id)), type = 'response')

#Create Aggregate Dataset with Observed and Expected Events as well as N Broken Out by Proning Status
df_agg_para_prone_status_sp <- df |>
  group_by(hospital_id, prone_48, study_period) |>
  filter(!is.na(hospital_id)) |>
  summarise(
    n_patients = n(),
    observed_paralytics = sum(any_paralytic_48, na.rm=TRUE),
    paralytics_rate_observed = mean(any_paralytic_48, na.rm=TRUE),
    paralytics_rate_adjust = mean(paralytics_propensity, na.rm = TRUE)
  ) |>
  ungroup() |>
  filter(!is.na(hospital_id)) |>
  mutate(expected_paralytics=round((paralytics_rate_adjust*n_patients), digits = 0)) |>
  mutate(not_paralytics=n_patients-observed_paralytics)

#Save CSV
write.csv(df_agg_para_prone_status_sp, paste0(project_location, '/project_output_UPLOAD/', site, '_aggregate_expected_paralytics_wprone_Status_sp.csv'))

```

```{r}
cat('This code is DONE!!! Thank you for your support for this CLIF project!')
```
